/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/codegen. DO NOT EDIT.

package convert

import (
	v1alpha2 "github.com/akuityio/provider-crossplane-akuity/apis/core/v1alpha2"
	glue "github.com/akuityio/provider-crossplane-akuity/internal/convert/glue"
	akuitytypes "github.com/akuityio/provider-crossplane-akuity/internal/types/generated/akuity/v1alpha1"
)

// AIConfigSpecToAPI converts the curated v1alpha2 AIConfig into the Akuity API AIConfig wire type.
func AIConfigSpecToAPI(in *v1alpha2.AIConfig) *akuitytypes.AIConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AIConfig{}
	if in.Runbooks != nil {
		out.Runbooks = make([]*akuitytypes.Runbook, 0, len(in.Runbooks))
		for _, item := range in.Runbooks {
			out.Runbooks = append(out.Runbooks, RunbookSpecToAPI(item))
		}
	}
	out.Incidents = IncidentsConfigSpecToAPI(in.Incidents)
	out.ArgocdSlackService = in.ArgocdSlackService
	out.ArgocdSlackChannels = in.ArgocdSlackChannels
	if in.RunbookRepos != nil {
		out.RunbookRepos = make([]*akuitytypes.RunbookRepo, 0, len(in.RunbookRepos))
		for _, item := range in.RunbookRepos {
			out.RunbookRepos = append(out.RunbookRepos, RunbookRepoSpecToAPI(item))
		}
	}
	return out
}

// AIConfigAPIToSpec converts the Akuity API AIConfig wire type back into the curated v1alpha2 AIConfig.
func AIConfigAPIToSpec(in *akuitytypes.AIConfig) *v1alpha2.AIConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AIConfig{}
	if in.Runbooks != nil {
		out.Runbooks = make([]*v1alpha2.Runbook, 0, len(in.Runbooks))
		for _, item := range in.Runbooks {
			out.Runbooks = append(out.Runbooks, RunbookAPIToSpec(item))
		}
	}
	out.Incidents = IncidentsConfigAPIToSpec(in.Incidents)
	out.ArgocdSlackService = in.ArgocdSlackService
	out.ArgocdSlackChannels = in.ArgocdSlackChannels
	if in.RunbookRepos != nil {
		out.RunbookRepos = make([]*v1alpha2.RunbookRepo, 0, len(in.RunbookRepos))
		for _, item := range in.RunbookRepos {
			out.RunbookRepos = append(out.RunbookRepos, RunbookRepoAPIToSpec(item))
		}
	}
	return out
}

// AdditionalAttributeRuleSpecToAPI converts the curated v1alpha2 AdditionalAttributeRule into the Akuity API AdditionalAttributeRule wire type.
func AdditionalAttributeRuleSpecToAPI(in *v1alpha2.AdditionalAttributeRule) *akuitytypes.AdditionalAttributeRule {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AdditionalAttributeRule{}
	out.Group = in.Group
	out.Kind = in.Kind
	out.Annotations = in.Annotations
	out.Labels = in.Labels
	out.Namespace = in.Namespace
	return out
}

// AdditionalAttributeRuleAPIToSpec converts the Akuity API AdditionalAttributeRule wire type back into the curated v1alpha2 AdditionalAttributeRule.
func AdditionalAttributeRuleAPIToSpec(in *akuitytypes.AdditionalAttributeRule) *v1alpha2.AdditionalAttributeRule {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AdditionalAttributeRule{}
	out.Group = in.Group
	out.Kind = in.Kind
	out.Annotations = in.Annotations
	out.Labels = in.Labels
	out.Namespace = in.Namespace
	return out
}

// AgentPermissionsRuleSpecToAPI converts the curated v1alpha2 AgentPermissionsRule into the Akuity API AgentPermissionsRule wire type.
func AgentPermissionsRuleSpecToAPI(in *v1alpha2.AgentPermissionsRule) *akuitytypes.AgentPermissionsRule {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AgentPermissionsRule{}
	out.ApiGroups = in.ApiGroups
	out.Resources = in.Resources
	out.Verbs = in.Verbs
	return out
}

// AgentPermissionsRuleAPIToSpec converts the Akuity API AgentPermissionsRule wire type back into the curated v1alpha2 AgentPermissionsRule.
func AgentPermissionsRuleAPIToSpec(in *akuitytypes.AgentPermissionsRule) *v1alpha2.AgentPermissionsRule {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AgentPermissionsRule{}
	out.ApiGroups = in.ApiGroups
	out.Resources = in.Resources
	out.Verbs = in.Verbs
	return out
}

// AkuityIntelligenceExtensionSpecToAPI converts the curated v1alpha2 AkuityIntelligenceExtension into the Akuity API AkuityIntelligenceExtension wire type.
func AkuityIntelligenceExtensionSpecToAPI(in *v1alpha2.AkuityIntelligenceExtension) *akuitytypes.AkuityIntelligenceExtension {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AkuityIntelligenceExtension{}
	out.Enabled = in.Enabled
	out.AllowedUsernames = in.AllowedUsernames
	out.AllowedGroups = in.AllowedGroups
	out.AiSupportEngineerEnabled = in.AiSupportEngineerEnabled
	out.ModelVersion = in.ModelVersion
	return out
}

// AkuityIntelligenceExtensionAPIToSpec converts the Akuity API AkuityIntelligenceExtension wire type back into the curated v1alpha2 AkuityIntelligenceExtension.
func AkuityIntelligenceExtensionAPIToSpec(in *akuitytypes.AkuityIntelligenceExtension) *v1alpha2.AkuityIntelligenceExtension {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AkuityIntelligenceExtension{}
	out.Enabled = in.Enabled
	out.AllowedUsernames = in.AllowedUsernames
	out.AllowedGroups = in.AllowedGroups
	out.AiSupportEngineerEnabled = in.AiSupportEngineerEnabled
	out.ModelVersion = in.ModelVersion
	return out
}

// AppInAnyNamespaceConfigSpecToAPI converts the curated v1alpha2 AppInAnyNamespaceConfig into the Akuity API AppInAnyNamespaceConfig wire type.
func AppInAnyNamespaceConfigSpecToAPI(in *v1alpha2.AppInAnyNamespaceConfig) *akuitytypes.AppInAnyNamespaceConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AppInAnyNamespaceConfig{}
	out.Enabled = in.Enabled
	return out
}

// AppInAnyNamespaceConfigAPIToSpec converts the Akuity API AppInAnyNamespaceConfig wire type back into the curated v1alpha2 AppInAnyNamespaceConfig.
func AppInAnyNamespaceConfigAPIToSpec(in *akuitytypes.AppInAnyNamespaceConfig) *v1alpha2.AppInAnyNamespaceConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AppInAnyNamespaceConfig{}
	out.Enabled = in.Enabled
	return out
}

// AppReconciliationsRateLimitingSpecToAPI converts the curated v1alpha2 AppReconciliationsRateLimiting into the Akuity API AppReconciliationsRateLimiting wire type.
func AppReconciliationsRateLimitingSpecToAPI(in *v1alpha2.AppReconciliationsRateLimiting) *akuitytypes.AppReconciliationsRateLimiting {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AppReconciliationsRateLimiting{}
	out.BucketRateLimiting = BucketRateLimitingSpecToAPI(in.BucketRateLimiting)
	out.ItemRateLimiting = ItemRateLimitingSpecToAPI(in.ItemRateLimiting)
	return out
}

// AppReconciliationsRateLimitingAPIToSpec converts the Akuity API AppReconciliationsRateLimiting wire type back into the curated v1alpha2 AppReconciliationsRateLimiting.
func AppReconciliationsRateLimitingAPIToSpec(in *akuitytypes.AppReconciliationsRateLimiting) *v1alpha2.AppReconciliationsRateLimiting {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AppReconciliationsRateLimiting{}
	out.BucketRateLimiting = BucketRateLimitingAPIToSpec(in.BucketRateLimiting)
	out.ItemRateLimiting = ItemRateLimitingAPIToSpec(in.ItemRateLimiting)
	return out
}

// AppSetDelegateSpecToAPI converts the curated v1alpha2 AppSetDelegate into the Akuity API AppSetDelegate wire type.
func AppSetDelegateSpecToAPI(in *v1alpha2.AppSetDelegate) *akuitytypes.AppSetDelegate {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AppSetDelegate{}
	out.ManagedCluster = ManagedClusterSpecToAPI(in.ManagedCluster)
	return out
}

// AppSetDelegateAPIToSpec converts the Akuity API AppSetDelegate wire type back into the curated v1alpha2 AppSetDelegate.
func AppSetDelegateAPIToSpec(in *akuitytypes.AppSetDelegate) *v1alpha2.AppSetDelegate {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AppSetDelegate{}
	out.ManagedCluster = ManagedClusterAPIToSpec(in.ManagedCluster)
	return out
}

// ApplicationSetExtensionSpecToAPI converts the curated v1alpha2 ApplicationSetExtension into the Akuity API ApplicationSetExtension wire type.
func ApplicationSetExtensionSpecToAPI(in *v1alpha2.ApplicationSetExtension) *akuitytypes.ApplicationSetExtension {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ApplicationSetExtension{}
	out.Enabled = in.Enabled
	return out
}

// ApplicationSetExtensionAPIToSpec converts the Akuity API ApplicationSetExtension wire type back into the curated v1alpha2 ApplicationSetExtension.
func ApplicationSetExtensionAPIToSpec(in *akuitytypes.ApplicationSetExtension) *v1alpha2.ApplicationSetExtension {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ApplicationSetExtension{}
	out.Enabled = in.Enabled
	return out
}

// AppsetPluginsSpecToAPI converts the curated v1alpha2 AppsetPlugins into the Akuity API AppsetPlugins wire type.
func AppsetPluginsSpecToAPI(in *v1alpha2.AppsetPlugins) *akuitytypes.AppsetPlugins {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AppsetPlugins{}
	out.Name = in.Name
	out.Token = in.Token
	out.BaseUrl = in.BaseUrl
	out.RequestTimeout = in.RequestTimeout
	return out
}

// AppsetPluginsAPIToSpec converts the Akuity API AppsetPlugins wire type back into the curated v1alpha2 AppsetPlugins.
func AppsetPluginsAPIToSpec(in *akuitytypes.AppsetPlugins) *v1alpha2.AppsetPlugins {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AppsetPlugins{}
	out.Name = in.Name
	out.Token = in.Token
	out.BaseUrl = in.BaseUrl
	out.RequestTimeout = in.RequestTimeout
	return out
}

// AppsetPolicySpecToAPI converts the curated v1alpha2 AppsetPolicy into the Akuity API AppsetPolicy wire type.
func AppsetPolicySpecToAPI(in *v1alpha2.AppsetPolicy) *akuitytypes.AppsetPolicy {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AppsetPolicy{}
	out.Policy = in.Policy
	out.OverridePolicy = in.OverridePolicy
	return out
}

// AppsetPolicyAPIToSpec converts the Akuity API AppsetPolicy wire type back into the curated v1alpha2 AppsetPolicy.
func AppsetPolicyAPIToSpec(in *akuitytypes.AppsetPolicy) *v1alpha2.AppsetPolicy {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AppsetPolicy{}
	out.Policy = in.Policy
	out.OverridePolicy = in.OverridePolicy
	return out
}

// ArgoCDExtensionInstallEntrySpecToAPI converts the curated v1alpha2 ArgoCDExtensionInstallEntry into the Akuity API ArgoCDExtensionInstallEntry wire type.
func ArgoCDExtensionInstallEntrySpecToAPI(in *v1alpha2.ArgoCDExtensionInstallEntry) *akuitytypes.ArgoCDExtensionInstallEntry {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ArgoCDExtensionInstallEntry{}
	out.Id = in.Id
	out.Version = in.Version
	return out
}

// ArgoCDExtensionInstallEntryAPIToSpec converts the Akuity API ArgoCDExtensionInstallEntry wire type back into the curated v1alpha2 ArgoCDExtensionInstallEntry.
func ArgoCDExtensionInstallEntryAPIToSpec(in *akuitytypes.ArgoCDExtensionInstallEntry) *v1alpha2.ArgoCDExtensionInstallEntry {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ArgoCDExtensionInstallEntry{}
	out.Id = in.Id
	out.Version = in.Version
	return out
}

// ArgoCDSpecSpecToAPI converts the curated v1alpha2 ArgoCDSpec into the Akuity API ArgoCDSpec wire type.
func ArgoCDSpecSpecToAPI(in *v1alpha2.ArgoCDSpec) *akuitytypes.ArgoCDSpec {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ArgoCDSpec{}
	out.Description = in.Description
	out.Version = in.Version
	out.Shard = in.Shard
	out.InstanceSpec = *InstanceSpecSpecToAPI(&in.InstanceSpec)
	return out
}

// ArgoCDSpecAPIToSpec converts the Akuity API ArgoCDSpec wire type back into the curated v1alpha2 ArgoCDSpec.
func ArgoCDSpecAPIToSpec(in *akuitytypes.ArgoCDSpec) *v1alpha2.ArgoCDSpec {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ArgoCDSpec{}
	out.Description = in.Description
	out.Version = in.Version
	out.Shard = in.Shard
	out.InstanceSpec = *InstanceSpecAPIToSpec(&in.InstanceSpec)
	return out
}

// BucketRateLimitingSpecToAPI converts the curated v1alpha2 BucketRateLimiting into the Akuity API BucketRateLimiting wire type.
func BucketRateLimitingSpecToAPI(in *v1alpha2.BucketRateLimiting) *akuitytypes.BucketRateLimiting {
	if in == nil {
		return nil
	}
	out := &akuitytypes.BucketRateLimiting{}
	out.Enabled = in.Enabled
	out.BucketSize = in.BucketSize
	out.BucketQps = in.BucketQps
	return out
}

// BucketRateLimitingAPIToSpec converts the Akuity API BucketRateLimiting wire type back into the curated v1alpha2 BucketRateLimiting.
func BucketRateLimitingAPIToSpec(in *akuitytypes.BucketRateLimiting) *v1alpha2.BucketRateLimiting {
	if in == nil {
		return nil
	}
	out := &v1alpha2.BucketRateLimiting{}
	out.Enabled = in.Enabled
	out.BucketSize = in.BucketSize
	out.BucketQps = in.BucketQps
	return out
}

// ClusterAddonsExtensionSpecToAPI converts the curated v1alpha2 ClusterAddonsExtension into the Akuity API ClusterAddonsExtension wire type.
func ClusterAddonsExtensionSpecToAPI(in *v1alpha2.ClusterAddonsExtension) *akuitytypes.ClusterAddonsExtension {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ClusterAddonsExtension{}
	out.Enabled = in.Enabled
	out.AllowedUsernames = in.AllowedUsernames
	out.AllowedGroups = in.AllowedGroups
	return out
}

// ClusterAddonsExtensionAPIToSpec converts the Akuity API ClusterAddonsExtension wire type back into the curated v1alpha2 ClusterAddonsExtension.
func ClusterAddonsExtensionAPIToSpec(in *akuitytypes.ClusterAddonsExtension) *v1alpha2.ClusterAddonsExtension {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ClusterAddonsExtension{}
	out.Enabled = in.Enabled
	out.AllowedUsernames = in.AllowedUsernames
	out.AllowedGroups = in.AllowedGroups
	return out
}

// ClusterCustomizationSpecToAPI converts the curated v1alpha2 ClusterCustomization into the Akuity API ClusterCustomization wire type.
func ClusterCustomizationSpecToAPI(in *v1alpha2.ClusterCustomization) *akuitytypes.ClusterCustomization {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ClusterCustomization{}
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.Kustomization = glue.KustomizationStringToRaw(in.Kustomization)
	out.AppReplication = in.AppReplication
	out.RedisTunneling = in.RedisTunneling
	out.ServerSideDiffEnabled = in.ServerSideDiffEnabled
	return out
}

// ClusterCustomizationAPIToSpec converts the Akuity API ClusterCustomization wire type back into the curated v1alpha2 ClusterCustomization.
func ClusterCustomizationAPIToSpec(in *akuitytypes.ClusterCustomization) *v1alpha2.ClusterCustomization {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ClusterCustomization{}
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.Kustomization = glue.KustomizationRawToString(in.Kustomization)
	out.AppReplication = in.AppReplication
	out.RedisTunneling = in.RedisTunneling
	out.ServerSideDiffEnabled = in.ServerSideDiffEnabled
	return out
}

// ClusterSecretMappingSpecToAPI converts the curated v1alpha2 ClusterSecretMapping into the Akuity API ClusterSecretMapping wire type.
func ClusterSecretMappingSpecToAPI(in *v1alpha2.ClusterSecretMapping) *akuitytypes.ClusterSecretMapping {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ClusterSecretMapping{}
	out.Clusters = ObjectSelectorSpecToAPI(in.Clusters)
	out.Secrets = ObjectSelectorSpecToAPI(in.Secrets)
	return out
}

// ClusterSecretMappingAPIToSpec converts the Akuity API ClusterSecretMapping wire type back into the curated v1alpha2 ClusterSecretMapping.
func ClusterSecretMappingAPIToSpec(in *akuitytypes.ClusterSecretMapping) *v1alpha2.ClusterSecretMapping {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ClusterSecretMapping{}
	out.Clusters = ObjectSelectorAPIToSpec(in.Clusters)
	out.Secrets = ObjectSelectorAPIToSpec(in.Secrets)
	return out
}

// ConfigManagementToolVersionsSpecToAPI converts the curated v1alpha2 ConfigManagementToolVersions into the Akuity API ConfigManagementToolVersions wire type.
func ConfigManagementToolVersionsSpecToAPI(in *v1alpha2.ConfigManagementToolVersions) *akuitytypes.ConfigManagementToolVersions {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ConfigManagementToolVersions{}
	out.DefaultVersion = in.DefaultVersion
	out.AdditionalVersions = in.AdditionalVersions
	return out
}

// ConfigManagementToolVersionsAPIToSpec converts the Akuity API ConfigManagementToolVersions wire type back into the curated v1alpha2 ConfigManagementToolVersions.
func ConfigManagementToolVersionsAPIToSpec(in *akuitytypes.ConfigManagementToolVersions) *v1alpha2.ConfigManagementToolVersions {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ConfigManagementToolVersions{}
	out.DefaultVersion = in.DefaultVersion
	out.AdditionalVersions = in.AdditionalVersions
	return out
}

// CrossplaneExtensionSpecToAPI converts the curated v1alpha2 CrossplaneExtension into the Akuity API CrossplaneExtension wire type.
func CrossplaneExtensionSpecToAPI(in *v1alpha2.CrossplaneExtension) *akuitytypes.CrossplaneExtension {
	if in == nil {
		return nil
	}
	out := &akuitytypes.CrossplaneExtension{}
	if in.Resources != nil {
		out.Resources = make([]*akuitytypes.CrossplaneExtensionResource, 0, len(in.Resources))
		for _, item := range in.Resources {
			out.Resources = append(out.Resources, CrossplaneExtensionResourceSpecToAPI(item))
		}
	}
	return out
}

// CrossplaneExtensionAPIToSpec converts the Akuity API CrossplaneExtension wire type back into the curated v1alpha2 CrossplaneExtension.
func CrossplaneExtensionAPIToSpec(in *akuitytypes.CrossplaneExtension) *v1alpha2.CrossplaneExtension {
	if in == nil {
		return nil
	}
	out := &v1alpha2.CrossplaneExtension{}
	if in.Resources != nil {
		out.Resources = make([]*v1alpha2.CrossplaneExtensionResource, 0, len(in.Resources))
		for _, item := range in.Resources {
			out.Resources = append(out.Resources, CrossplaneExtensionResourceAPIToSpec(item))
		}
	}
	return out
}

// CrossplaneExtensionResourceSpecToAPI converts the curated v1alpha2 CrossplaneExtensionResource into the Akuity API CrossplaneExtensionResource wire type.
func CrossplaneExtensionResourceSpecToAPI(in *v1alpha2.CrossplaneExtensionResource) *akuitytypes.CrossplaneExtensionResource {
	if in == nil {
		return nil
	}
	out := &akuitytypes.CrossplaneExtensionResource{}
	out.Group = in.Group
	return out
}

// CrossplaneExtensionResourceAPIToSpec converts the Akuity API CrossplaneExtensionResource wire type back into the curated v1alpha2 CrossplaneExtensionResource.
func CrossplaneExtensionResourceAPIToSpec(in *akuitytypes.CrossplaneExtensionResource) *v1alpha2.CrossplaneExtensionResource {
	if in == nil {
		return nil
	}
	out := &v1alpha2.CrossplaneExtensionResource{}
	out.Group = in.Group
	return out
}

// CustomDeprecatedAPISpecToAPI converts the curated v1alpha2 CustomDeprecatedAPI into the Akuity API CustomDeprecatedAPI wire type.
func CustomDeprecatedAPISpecToAPI(in *v1alpha2.CustomDeprecatedAPI) *akuitytypes.CustomDeprecatedAPI {
	if in == nil {
		return nil
	}
	out := &akuitytypes.CustomDeprecatedAPI{}
	out.ApiVersion = in.ApiVersion
	out.NewApiVersion = in.NewApiVersion
	out.DeprecatedInKubernetesVersion = in.DeprecatedInKubernetesVersion
	out.UnavailableInKubernetesVersion = in.UnavailableInKubernetesVersion
	return out
}

// CustomDeprecatedAPIAPIToSpec converts the Akuity API CustomDeprecatedAPI wire type back into the curated v1alpha2 CustomDeprecatedAPI.
func CustomDeprecatedAPIAPIToSpec(in *akuitytypes.CustomDeprecatedAPI) *v1alpha2.CustomDeprecatedAPI {
	if in == nil {
		return nil
	}
	out := &v1alpha2.CustomDeprecatedAPI{}
	out.ApiVersion = in.ApiVersion
	out.NewApiVersion = in.NewApiVersion
	out.DeprecatedInKubernetesVersion = in.DeprecatedInKubernetesVersion
	out.UnavailableInKubernetesVersion = in.UnavailableInKubernetesVersion
	return out
}

// CveScanConfigSpecToAPI converts the curated v1alpha2 CveScanConfig into the Akuity API CveScanConfig wire type.
func CveScanConfigSpecToAPI(in *v1alpha2.CveScanConfig) *akuitytypes.CveScanConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.CveScanConfig{}
	out.ScanEnabled = in.ScanEnabled
	out.RescanInterval = in.RescanInterval
	return out
}

// CveScanConfigAPIToSpec converts the Akuity API CveScanConfig wire type back into the curated v1alpha2 CveScanConfig.
func CveScanConfigAPIToSpec(in *akuitytypes.CveScanConfig) *v1alpha2.CveScanConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.CveScanConfig{}
	out.ScanEnabled = in.ScanEnabled
	out.RescanInterval = in.RescanInterval
	return out
}

// HostAliasesSpecToAPI converts the curated v1alpha2 HostAliases into the Akuity API HostAliases wire type.
func HostAliasesSpecToAPI(in *v1alpha2.HostAliases) *akuitytypes.HostAliases {
	if in == nil {
		return nil
	}
	out := &akuitytypes.HostAliases{}
	out.Ip = in.Ip
	out.Hostnames = in.Hostnames
	return out
}

// HostAliasesAPIToSpec converts the Akuity API HostAliases wire type back into the curated v1alpha2 HostAliases.
func HostAliasesAPIToSpec(in *akuitytypes.HostAliases) *v1alpha2.HostAliases {
	if in == nil {
		return nil
	}
	out := &v1alpha2.HostAliases{}
	out.Ip = in.Ip
	out.Hostnames = in.Hostnames
	return out
}

// IPAllowListEntrySpecToAPI converts the curated v1alpha2 IPAllowListEntry into the Akuity API IPAllowListEntry wire type.
func IPAllowListEntrySpecToAPI(in *v1alpha2.IPAllowListEntry) *akuitytypes.IPAllowListEntry {
	if in == nil {
		return nil
	}
	out := &akuitytypes.IPAllowListEntry{}
	out.Ip = in.Ip
	out.Description = in.Description
	return out
}

// IPAllowListEntryAPIToSpec converts the Akuity API IPAllowListEntry wire type back into the curated v1alpha2 IPAllowListEntry.
func IPAllowListEntryAPIToSpec(in *akuitytypes.IPAllowListEntry) *v1alpha2.IPAllowListEntry {
	if in == nil {
		return nil
	}
	out := &v1alpha2.IPAllowListEntry{}
	out.Ip = in.Ip
	out.Description = in.Description
	return out
}

// ImageUpdaterDelegateSpecToAPI converts the curated v1alpha2 ImageUpdaterDelegate into the Akuity API ImageUpdaterDelegate wire type.
func ImageUpdaterDelegateSpecToAPI(in *v1alpha2.ImageUpdaterDelegate) *akuitytypes.ImageUpdaterDelegate {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ImageUpdaterDelegate{}
	out.ControlPlane = in.ControlPlane
	out.ManagedCluster = ManagedClusterSpecToAPI(in.ManagedCluster)
	return out
}

// ImageUpdaterDelegateAPIToSpec converts the Akuity API ImageUpdaterDelegate wire type back into the curated v1alpha2 ImageUpdaterDelegate.
func ImageUpdaterDelegateAPIToSpec(in *akuitytypes.ImageUpdaterDelegate) *v1alpha2.ImageUpdaterDelegate {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ImageUpdaterDelegate{}
	out.ControlPlane = in.ControlPlane
	out.ManagedCluster = ManagedClusterAPIToSpec(in.ManagedCluster)
	return out
}

// IncidentInvestigationApprovalConfigSpecToAPI converts the curated v1alpha2 IncidentInvestigationApprovalConfig into the Akuity API IncidentInvestigationApprovalConfig wire type.
func IncidentInvestigationApprovalConfigSpecToAPI(in *v1alpha2.IncidentInvestigationApprovalConfig) *akuitytypes.IncidentInvestigationApprovalConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.IncidentInvestigationApprovalConfig{}
	if in.Scopes != nil {
		out.Scopes = make([]*akuitytypes.IncidentInvestigationApprovalScope, 0, len(in.Scopes))
		for _, item := range in.Scopes {
			out.Scopes = append(out.Scopes, IncidentInvestigationApprovalScopeSpecToAPI(item))
		}
	}
	return out
}

// IncidentInvestigationApprovalConfigAPIToSpec converts the Akuity API IncidentInvestigationApprovalConfig wire type back into the curated v1alpha2 IncidentInvestigationApprovalConfig.
func IncidentInvestigationApprovalConfigAPIToSpec(in *akuitytypes.IncidentInvestigationApprovalConfig) *v1alpha2.IncidentInvestigationApprovalConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.IncidentInvestigationApprovalConfig{}
	if in.Scopes != nil {
		out.Scopes = make([]*v1alpha2.IncidentInvestigationApprovalScope, 0, len(in.Scopes))
		for _, item := range in.Scopes {
			out.Scopes = append(out.Scopes, IncidentInvestigationApprovalScopeAPIToSpec(item))
		}
	}
	return out
}

// IncidentInvestigationApprovalScopeSpecToAPI converts the curated v1alpha2 IncidentInvestigationApprovalScope into the Akuity API IncidentInvestigationApprovalScope wire type.
func IncidentInvestigationApprovalScopeSpecToAPI(in *v1alpha2.IncidentInvestigationApprovalScope) *akuitytypes.IncidentInvestigationApprovalScope {
	if in == nil {
		return nil
	}
	out := &akuitytypes.IncidentInvestigationApprovalScope{}
	out.ArgocdApplications = in.ArgocdApplications
	out.K8SNamespaces = in.K8SNamespaces
	out.Clusters = in.Clusters
	out.ConsecutiveAutoClosures = in.ConsecutiveAutoClosures
	return out
}

// IncidentInvestigationApprovalScopeAPIToSpec converts the Akuity API IncidentInvestigationApprovalScope wire type back into the curated v1alpha2 IncidentInvestigationApprovalScope.
func IncidentInvestigationApprovalScopeAPIToSpec(in *akuitytypes.IncidentInvestigationApprovalScope) *v1alpha2.IncidentInvestigationApprovalScope {
	if in == nil {
		return nil
	}
	out := &v1alpha2.IncidentInvestigationApprovalScope{}
	out.ArgocdApplications = in.ArgocdApplications
	out.K8SNamespaces = in.K8SNamespaces
	out.Clusters = in.Clusters
	out.ConsecutiveAutoClosures = in.ConsecutiveAutoClosures
	return out
}

// IncidentWebhookConfigSpecToAPI converts the curated v1alpha2 IncidentWebhookConfig into the Akuity API IncidentWebhookConfig wire type.
func IncidentWebhookConfigSpecToAPI(in *v1alpha2.IncidentWebhookConfig) *akuitytypes.IncidentWebhookConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.IncidentWebhookConfig{}
	out.Name = in.Name
	out.DescriptionPath = in.DescriptionPath
	out.ClusterPath = in.ClusterPath
	out.K8SNamespacePath = in.K8SNamespacePath
	out.ArgocdApplicationNamePath = in.ArgocdApplicationNamePath
	out.ArgocdApplicationNamespacePath = in.ArgocdApplicationNamespacePath
	out.TitlePath = in.TitlePath
	return out
}

// IncidentWebhookConfigAPIToSpec converts the Akuity API IncidentWebhookConfig wire type back into the curated v1alpha2 IncidentWebhookConfig.
func IncidentWebhookConfigAPIToSpec(in *akuitytypes.IncidentWebhookConfig) *v1alpha2.IncidentWebhookConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.IncidentWebhookConfig{}
	out.Name = in.Name
	out.DescriptionPath = in.DescriptionPath
	out.ClusterPath = in.ClusterPath
	out.K8SNamespacePath = in.K8SNamespacePath
	out.ArgocdApplicationNamePath = in.ArgocdApplicationNamePath
	out.ArgocdApplicationNamespacePath = in.ArgocdApplicationNamespacePath
	out.TitlePath = in.TitlePath
	return out
}

// IncidentsConfigSpecToAPI converts the curated v1alpha2 IncidentsConfig into the Akuity API IncidentsConfig wire type.
func IncidentsConfigSpecToAPI(in *v1alpha2.IncidentsConfig) *akuitytypes.IncidentsConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.IncidentsConfig{}
	if in.Triggers != nil {
		out.Triggers = make([]*akuitytypes.TargetSelector, 0, len(in.Triggers))
		for _, item := range in.Triggers {
			out.Triggers = append(out.Triggers, TargetSelectorSpecToAPI(item))
		}
	}
	if in.Webhooks != nil {
		out.Webhooks = make([]*akuitytypes.IncidentWebhookConfig, 0, len(in.Webhooks))
		for _, item := range in.Webhooks {
			out.Webhooks = append(out.Webhooks, IncidentWebhookConfigSpecToAPI(item))
		}
	}
	out.Grouping = IncidentsGroupingConfigSpecToAPI(in.Grouping)
	out.InvestigationApproval = IncidentInvestigationApprovalConfigSpecToAPI(in.InvestigationApproval)
	return out
}

// IncidentsConfigAPIToSpec converts the Akuity API IncidentsConfig wire type back into the curated v1alpha2 IncidentsConfig.
func IncidentsConfigAPIToSpec(in *akuitytypes.IncidentsConfig) *v1alpha2.IncidentsConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.IncidentsConfig{}
	if in.Triggers != nil {
		out.Triggers = make([]*v1alpha2.TargetSelector, 0, len(in.Triggers))
		for _, item := range in.Triggers {
			out.Triggers = append(out.Triggers, TargetSelectorAPIToSpec(item))
		}
	}
	if in.Webhooks != nil {
		out.Webhooks = make([]*v1alpha2.IncidentWebhookConfig, 0, len(in.Webhooks))
		for _, item := range in.Webhooks {
			out.Webhooks = append(out.Webhooks, IncidentWebhookConfigAPIToSpec(item))
		}
	}
	out.Grouping = IncidentsGroupingConfigAPIToSpec(in.Grouping)
	out.InvestigationApproval = IncidentInvestigationApprovalConfigAPIToSpec(in.InvestigationApproval)
	return out
}

// IncidentsGroupingConfigSpecToAPI converts the curated v1alpha2 IncidentsGroupingConfig into the Akuity API IncidentsGroupingConfig wire type.
func IncidentsGroupingConfigSpecToAPI(in *v1alpha2.IncidentsGroupingConfig) *akuitytypes.IncidentsGroupingConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.IncidentsGroupingConfig{}
	out.K8SNamespaces = in.K8SNamespaces
	out.ArgocdApplicationNames = in.ArgocdApplicationNames
	return out
}

// IncidentsGroupingConfigAPIToSpec converts the Akuity API IncidentsGroupingConfig wire type back into the curated v1alpha2 IncidentsGroupingConfig.
func IncidentsGroupingConfigAPIToSpec(in *akuitytypes.IncidentsGroupingConfig) *v1alpha2.IncidentsGroupingConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.IncidentsGroupingConfig{}
	out.K8SNamespaces = in.K8SNamespaces
	out.ArgocdApplicationNames = in.ArgocdApplicationNames
	return out
}

// InstanceSpecSpecToAPI converts the curated v1alpha2 ArgoCDInstanceSpec into the Akuity API InstanceSpec wire type.
func InstanceSpecSpecToAPI(in *v1alpha2.ArgoCDInstanceSpec) *akuitytypes.InstanceSpec {
	if in == nil {
		return nil
	}
	out := &akuitytypes.InstanceSpec{}
	if in.IpAllowList != nil {
		out.IpAllowList = make([]*akuitytypes.IPAllowListEntry, 0, len(in.IpAllowList))
		for _, item := range in.IpAllowList {
			out.IpAllowList = append(out.IpAllowList, IPAllowListEntrySpecToAPI(item))
		}
	}
	out.Subdomain = in.Subdomain
	out.DeclarativeManagementEnabled = in.DeclarativeManagementEnabled
	if in.Extensions != nil {
		out.Extensions = make([]*akuitytypes.ArgoCDExtensionInstallEntry, 0, len(in.Extensions))
		for _, item := range in.Extensions {
			out.Extensions = append(out.Extensions, ArgoCDExtensionInstallEntrySpecToAPI(item))
		}
	}
	out.ClusterCustomizationDefaults = ClusterCustomizationSpecToAPI(in.ClusterCustomizationDefaults)
	out.ImageUpdaterEnabled = in.ImageUpdaterEnabled
	out.BackendIpAllowListEnabled = in.BackendIpAllowListEnabled
	out.RepoServerDelegate = RepoServerDelegateSpecToAPI(in.RepoServerDelegate)
	out.AuditExtensionEnabled = in.AuditExtensionEnabled
	out.SyncHistoryExtensionEnabled = in.SyncHistoryExtensionEnabled
	out.CrossplaneExtension = CrossplaneExtensionSpecToAPI(in.CrossplaneExtension)
	out.ImageUpdaterDelegate = ImageUpdaterDelegateSpecToAPI(in.ImageUpdaterDelegate)
	out.AppSetDelegate = AppSetDelegateSpecToAPI(in.AppSetDelegate)
	out.AssistantExtensionEnabled = in.AssistantExtensionEnabled
	out.AppsetPolicy = AppsetPolicySpecToAPI(in.AppsetPolicy)
	if in.HostAliases != nil {
		out.HostAliases = make([]*akuitytypes.HostAliases, 0, len(in.HostAliases))
		for _, item := range in.HostAliases {
			out.HostAliases = append(out.HostAliases, HostAliasesSpecToAPI(item))
		}
	}
	if in.AgentPermissionsRules != nil {
		out.AgentPermissionsRules = make([]*akuitytypes.AgentPermissionsRule, 0, len(in.AgentPermissionsRules))
		for _, item := range in.AgentPermissionsRules {
			out.AgentPermissionsRules = append(out.AgentPermissionsRules, AgentPermissionsRuleSpecToAPI(item))
		}
	}
	out.Fqdn = in.Fqdn
	out.MultiClusterK8SDashboardEnabled = in.MultiClusterK8SDashboardEnabled
	out.AkuityIntelligenceExtension = AkuityIntelligenceExtensionSpecToAPI(in.AkuityIntelligenceExtension)
	out.ImageUpdaterVersion = in.ImageUpdaterVersion
	if in.CustomDeprecatedApis != nil {
		out.CustomDeprecatedApis = make([]*akuitytypes.CustomDeprecatedAPI, 0, len(in.CustomDeprecatedApis))
		for _, item := range in.CustomDeprecatedApis {
			out.CustomDeprecatedApis = append(out.CustomDeprecatedApis, CustomDeprecatedAPISpecToAPI(item))
		}
	}
	out.KubeVisionConfig = KubeVisionConfigSpecToAPI(in.KubeVisionConfig)
	out.AppInAnyNamespaceConfig = AppInAnyNamespaceConfigSpecToAPI(in.AppInAnyNamespaceConfig)
	out.Basepath = in.Basepath
	out.AppsetProgressiveSyncsEnabled = in.AppsetProgressiveSyncsEnabled
	out.Secrets = SecretsManagementConfigSpecToAPI(in.Secrets)
	if in.AppsetPlugins != nil {
		out.AppsetPlugins = make([]*akuitytypes.AppsetPlugins, 0, len(in.AppsetPlugins))
		for _, item := range in.AppsetPlugins {
			out.AppsetPlugins = append(out.AppsetPlugins, AppsetPluginsSpecToAPI(item))
		}
	}
	out.ApplicationSetExtension = ApplicationSetExtensionSpecToAPI(in.ApplicationSetExtension)
	out.AppReconciliationsRateLimiting = AppReconciliationsRateLimitingSpecToAPI(in.AppReconciliationsRateLimiting)
	out.MetricsIngressUsername = in.MetricsIngressUsername
	out.MetricsIngressPasswordHash = in.MetricsIngressPasswordHash
	out.PrivilegedNotificationCluster = in.PrivilegedNotificationCluster
	out.ClusterAddonsExtension = ClusterAddonsExtensionSpecToAPI(in.ClusterAddonsExtension)
	out.ManifestGeneration = ManifestGenerationSpecToAPI(in.ManifestGeneration)
	return out
}

// InstanceSpecAPIToSpec converts the Akuity API InstanceSpec wire type back into the curated v1alpha2 ArgoCDInstanceSpec.
func InstanceSpecAPIToSpec(in *akuitytypes.InstanceSpec) *v1alpha2.ArgoCDInstanceSpec {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ArgoCDInstanceSpec{}
	if in.IpAllowList != nil {
		out.IpAllowList = make([]*v1alpha2.IPAllowListEntry, 0, len(in.IpAllowList))
		for _, item := range in.IpAllowList {
			out.IpAllowList = append(out.IpAllowList, IPAllowListEntryAPIToSpec(item))
		}
	}
	out.Subdomain = in.Subdomain
	out.DeclarativeManagementEnabled = in.DeclarativeManagementEnabled
	if in.Extensions != nil {
		out.Extensions = make([]*v1alpha2.ArgoCDExtensionInstallEntry, 0, len(in.Extensions))
		for _, item := range in.Extensions {
			out.Extensions = append(out.Extensions, ArgoCDExtensionInstallEntryAPIToSpec(item))
		}
	}
	out.ClusterCustomizationDefaults = ClusterCustomizationAPIToSpec(in.ClusterCustomizationDefaults)
	out.ImageUpdaterEnabled = in.ImageUpdaterEnabled
	out.BackendIpAllowListEnabled = in.BackendIpAllowListEnabled
	out.RepoServerDelegate = RepoServerDelegateAPIToSpec(in.RepoServerDelegate)
	out.AuditExtensionEnabled = in.AuditExtensionEnabled
	out.SyncHistoryExtensionEnabled = in.SyncHistoryExtensionEnabled
	out.CrossplaneExtension = CrossplaneExtensionAPIToSpec(in.CrossplaneExtension)
	out.ImageUpdaterDelegate = ImageUpdaterDelegateAPIToSpec(in.ImageUpdaterDelegate)
	out.AppSetDelegate = AppSetDelegateAPIToSpec(in.AppSetDelegate)
	out.AssistantExtensionEnabled = in.AssistantExtensionEnabled
	out.AppsetPolicy = AppsetPolicyAPIToSpec(in.AppsetPolicy)
	if in.HostAliases != nil {
		out.HostAliases = make([]*v1alpha2.HostAliases, 0, len(in.HostAliases))
		for _, item := range in.HostAliases {
			out.HostAliases = append(out.HostAliases, HostAliasesAPIToSpec(item))
		}
	}
	if in.AgentPermissionsRules != nil {
		out.AgentPermissionsRules = make([]*v1alpha2.AgentPermissionsRule, 0, len(in.AgentPermissionsRules))
		for _, item := range in.AgentPermissionsRules {
			out.AgentPermissionsRules = append(out.AgentPermissionsRules, AgentPermissionsRuleAPIToSpec(item))
		}
	}
	out.Fqdn = in.Fqdn
	out.MultiClusterK8SDashboardEnabled = in.MultiClusterK8SDashboardEnabled
	out.AkuityIntelligenceExtension = AkuityIntelligenceExtensionAPIToSpec(in.AkuityIntelligenceExtension)
	out.ImageUpdaterVersion = in.ImageUpdaterVersion
	if in.CustomDeprecatedApis != nil {
		out.CustomDeprecatedApis = make([]*v1alpha2.CustomDeprecatedAPI, 0, len(in.CustomDeprecatedApis))
		for _, item := range in.CustomDeprecatedApis {
			out.CustomDeprecatedApis = append(out.CustomDeprecatedApis, CustomDeprecatedAPIAPIToSpec(item))
		}
	}
	out.KubeVisionConfig = KubeVisionConfigAPIToSpec(in.KubeVisionConfig)
	out.AppInAnyNamespaceConfig = AppInAnyNamespaceConfigAPIToSpec(in.AppInAnyNamespaceConfig)
	out.Basepath = in.Basepath
	out.AppsetProgressiveSyncsEnabled = in.AppsetProgressiveSyncsEnabled
	out.Secrets = SecretsManagementConfigAPIToSpec(in.Secrets)
	if in.AppsetPlugins != nil {
		out.AppsetPlugins = make([]*v1alpha2.AppsetPlugins, 0, len(in.AppsetPlugins))
		for _, item := range in.AppsetPlugins {
			out.AppsetPlugins = append(out.AppsetPlugins, AppsetPluginsAPIToSpec(item))
		}
	}
	out.ApplicationSetExtension = ApplicationSetExtensionAPIToSpec(in.ApplicationSetExtension)
	out.AppReconciliationsRateLimiting = AppReconciliationsRateLimitingAPIToSpec(in.AppReconciliationsRateLimiting)
	out.MetricsIngressUsername = in.MetricsIngressUsername
	out.MetricsIngressPasswordHash = in.MetricsIngressPasswordHash
	out.PrivilegedNotificationCluster = in.PrivilegedNotificationCluster
	out.ClusterAddonsExtension = ClusterAddonsExtensionAPIToSpec(in.ClusterAddonsExtension)
	out.ManifestGeneration = ManifestGenerationAPIToSpec(in.ManifestGeneration)
	return out
}

// ItemRateLimitingSpecToAPI converts the curated v1alpha2 ItemRateLimiting into the Akuity API ItemRateLimiting wire type.
func ItemRateLimitingSpecToAPI(in *v1alpha2.ItemRateLimiting) *akuitytypes.ItemRateLimiting {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ItemRateLimiting{}
	out.Enabled = in.Enabled
	out.FailureCooldown = in.FailureCooldown
	out.BaseDelay = in.BaseDelay
	out.MaxDelay = in.MaxDelay
	out.BackoffFactor = in.BackoffFactor
	return out
}

// ItemRateLimitingAPIToSpec converts the Akuity API ItemRateLimiting wire type back into the curated v1alpha2 ItemRateLimiting.
func ItemRateLimitingAPIToSpec(in *akuitytypes.ItemRateLimiting) *v1alpha2.ItemRateLimiting {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ItemRateLimiting{}
	out.Enabled = in.Enabled
	out.FailureCooldown = in.FailureCooldown
	out.BaseDelay = in.BaseDelay
	out.MaxDelay = in.MaxDelay
	out.BackoffFactor = in.BackoffFactor
	return out
}

// KubeVisionConfigSpecToAPI converts the curated v1alpha2 KubeVisionConfig into the Akuity API KubeVisionConfig wire type.
func KubeVisionConfigSpecToAPI(in *v1alpha2.KubeVisionConfig) *akuitytypes.KubeVisionConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KubeVisionConfig{}
	out.CveScanConfig = CveScanConfigSpecToAPI(in.CveScanConfig)
	out.AiConfig = AIConfigSpecToAPI(in.AiConfig)
	if in.AdditionalAttributes != nil {
		out.AdditionalAttributes = make([]*akuitytypes.AdditionalAttributeRule, 0, len(in.AdditionalAttributes))
		for _, item := range in.AdditionalAttributes {
			out.AdditionalAttributes = append(out.AdditionalAttributes, AdditionalAttributeRuleSpecToAPI(item))
		}
	}
	return out
}

// KubeVisionConfigAPIToSpec converts the Akuity API KubeVisionConfig wire type back into the curated v1alpha2 KubeVisionConfig.
func KubeVisionConfigAPIToSpec(in *akuitytypes.KubeVisionConfig) *v1alpha2.KubeVisionConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KubeVisionConfig{}
	out.CveScanConfig = CveScanConfigAPIToSpec(in.CveScanConfig)
	out.AiConfig = AIConfigAPIToSpec(in.AiConfig)
	if in.AdditionalAttributes != nil {
		out.AdditionalAttributes = make([]*v1alpha2.AdditionalAttributeRule, 0, len(in.AdditionalAttributes))
		for _, item := range in.AdditionalAttributes {
			out.AdditionalAttributes = append(out.AdditionalAttributes, AdditionalAttributeRuleAPIToSpec(item))
		}
	}
	return out
}

// LabelSelectorRequirementSpecToAPI converts the curated v1alpha2 LabelSelectorRequirement into the Akuity API LabelSelectorRequirement wire type.
func LabelSelectorRequirementSpecToAPI(in *v1alpha2.LabelSelectorRequirement) *akuitytypes.LabelSelectorRequirement {
	if in == nil {
		return nil
	}
	out := &akuitytypes.LabelSelectorRequirement{}
	out.Key = in.Key
	out.Operator = in.Operator
	out.Values = in.Values
	return out
}

// LabelSelectorRequirementAPIToSpec converts the Akuity API LabelSelectorRequirement wire type back into the curated v1alpha2 LabelSelectorRequirement.
func LabelSelectorRequirementAPIToSpec(in *akuitytypes.LabelSelectorRequirement) *v1alpha2.LabelSelectorRequirement {
	if in == nil {
		return nil
	}
	out := &v1alpha2.LabelSelectorRequirement{}
	out.Key = in.Key
	out.Operator = in.Operator
	out.Values = in.Values
	return out
}

// ManagedClusterSpecToAPI converts the curated v1alpha2 ManagedCluster into the Akuity API ManagedCluster wire type.
func ManagedClusterSpecToAPI(in *v1alpha2.ManagedCluster) *akuitytypes.ManagedCluster {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ManagedCluster{}
	out.ClusterName = in.ClusterName
	return out
}

// ManagedClusterAPIToSpec converts the Akuity API ManagedCluster wire type back into the curated v1alpha2 ManagedCluster.
func ManagedClusterAPIToSpec(in *akuitytypes.ManagedCluster) *v1alpha2.ManagedCluster {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ManagedCluster{}
	out.ClusterName = in.ClusterName
	return out
}

// ManifestGenerationSpecToAPI converts the curated v1alpha2 ManifestGeneration into the Akuity API ManifestGeneration wire type.
func ManifestGenerationSpecToAPI(in *v1alpha2.ManifestGeneration) *akuitytypes.ManifestGeneration {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ManifestGeneration{}
	out.Kustomize = ConfigManagementToolVersionsSpecToAPI(in.Kustomize)
	return out
}

// ManifestGenerationAPIToSpec converts the Akuity API ManifestGeneration wire type back into the curated v1alpha2 ManifestGeneration.
func ManifestGenerationAPIToSpec(in *akuitytypes.ManifestGeneration) *v1alpha2.ManifestGeneration {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ManifestGeneration{}
	out.Kustomize = ConfigManagementToolVersionsAPIToSpec(in.Kustomize)
	return out
}

// ObjectSelectorSpecToAPI converts the curated v1alpha2 ObjectSelector into the Akuity API ObjectSelector wire type.
func ObjectSelectorSpecToAPI(in *v1alpha2.ObjectSelector) *akuitytypes.ObjectSelector {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ObjectSelector{}
	out.MatchLabels = in.MatchLabels
	if in.MatchExpressions != nil {
		out.MatchExpressions = make([]*akuitytypes.LabelSelectorRequirement, 0, len(in.MatchExpressions))
		for _, item := range in.MatchExpressions {
			out.MatchExpressions = append(out.MatchExpressions, LabelSelectorRequirementSpecToAPI(item))
		}
	}
	return out
}

// ObjectSelectorAPIToSpec converts the Akuity API ObjectSelector wire type back into the curated v1alpha2 ObjectSelector.
func ObjectSelectorAPIToSpec(in *akuitytypes.ObjectSelector) *v1alpha2.ObjectSelector {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ObjectSelector{}
	out.MatchLabels = in.MatchLabels
	if in.MatchExpressions != nil {
		out.MatchExpressions = make([]*v1alpha2.LabelSelectorRequirement, 0, len(in.MatchExpressions))
		for _, item := range in.MatchExpressions {
			out.MatchExpressions = append(out.MatchExpressions, LabelSelectorRequirementAPIToSpec(item))
		}
	}
	return out
}

// RepoServerDelegateSpecToAPI converts the curated v1alpha2 RepoServerDelegate into the Akuity API RepoServerDelegate wire type.
func RepoServerDelegateSpecToAPI(in *v1alpha2.RepoServerDelegate) *akuitytypes.RepoServerDelegate {
	if in == nil {
		return nil
	}
	out := &akuitytypes.RepoServerDelegate{}
	out.ControlPlane = in.ControlPlane
	out.ManagedCluster = ManagedClusterSpecToAPI(in.ManagedCluster)
	return out
}

// RepoServerDelegateAPIToSpec converts the Akuity API RepoServerDelegate wire type back into the curated v1alpha2 RepoServerDelegate.
func RepoServerDelegateAPIToSpec(in *akuitytypes.RepoServerDelegate) *v1alpha2.RepoServerDelegate {
	if in == nil {
		return nil
	}
	out := &v1alpha2.RepoServerDelegate{}
	out.ControlPlane = in.ControlPlane
	out.ManagedCluster = ManagedClusterAPIToSpec(in.ManagedCluster)
	return out
}

// RunbookSpecToAPI converts the curated v1alpha2 Runbook into the Akuity API Runbook wire type.
func RunbookSpecToAPI(in *v1alpha2.Runbook) *akuitytypes.Runbook {
	if in == nil {
		return nil
	}
	out := &akuitytypes.Runbook{}
	out.Name = in.Name
	out.Content = in.Content
	out.AppliedTo = TargetSelectorSpecToAPI(in.AppliedTo)
	out.SlackChannelNames = in.SlackChannelNames
	return out
}

// RunbookAPIToSpec converts the Akuity API Runbook wire type back into the curated v1alpha2 Runbook.
func RunbookAPIToSpec(in *akuitytypes.Runbook) *v1alpha2.Runbook {
	if in == nil {
		return nil
	}
	out := &v1alpha2.Runbook{}
	out.Name = in.Name
	out.Content = in.Content
	out.AppliedTo = TargetSelectorAPIToSpec(in.AppliedTo)
	out.SlackChannelNames = in.SlackChannelNames
	return out
}

// RunbookRepoSpecToAPI converts the curated v1alpha2 RunbookRepo into the Akuity API RunbookRepo wire type.
func RunbookRepoSpecToAPI(in *v1alpha2.RunbookRepo) *akuitytypes.RunbookRepo {
	if in == nil {
		return nil
	}
	out := &akuitytypes.RunbookRepo{}
	out.RepoUrl = in.RepoUrl
	out.Revision = in.Revision
	out.Path = in.Path
	if in.AppliedFor != nil {
		out.AppliedFor = make(map[string]*akuitytypes.TargetSelector, len(in.AppliedFor))
		for k, v := range in.AppliedFor {
			out.AppliedFor[k] = TargetSelectorSpecToAPI(v)
		}
	}
	return out
}

// RunbookRepoAPIToSpec converts the Akuity API RunbookRepo wire type back into the curated v1alpha2 RunbookRepo.
func RunbookRepoAPIToSpec(in *akuitytypes.RunbookRepo) *v1alpha2.RunbookRepo {
	if in == nil {
		return nil
	}
	out := &v1alpha2.RunbookRepo{}
	out.RepoUrl = in.RepoUrl
	out.Revision = in.Revision
	out.Path = in.Path
	if in.AppliedFor != nil {
		out.AppliedFor = make(map[string]*v1alpha2.TargetSelector, len(in.AppliedFor))
		for k, v := range in.AppliedFor {
			out.AppliedFor[k] = TargetSelectorAPIToSpec(v)
		}
	}
	return out
}

// SecretsManagementConfigSpecToAPI converts the curated v1alpha2 SecretsManagementConfig into the Akuity API SecretsManagementConfig wire type.
func SecretsManagementConfigSpecToAPI(in *v1alpha2.SecretsManagementConfig) *akuitytypes.SecretsManagementConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.SecretsManagementConfig{}
	if in.Sources != nil {
		out.Sources = make([]*akuitytypes.ClusterSecretMapping, 0, len(in.Sources))
		for _, item := range in.Sources {
			out.Sources = append(out.Sources, ClusterSecretMappingSpecToAPI(item))
		}
	}
	if in.Destinations != nil {
		out.Destinations = make([]*akuitytypes.ClusterSecretMapping, 0, len(in.Destinations))
		for _, item := range in.Destinations {
			out.Destinations = append(out.Destinations, ClusterSecretMappingSpecToAPI(item))
		}
	}
	return out
}

// SecretsManagementConfigAPIToSpec converts the Akuity API SecretsManagementConfig wire type back into the curated v1alpha2 SecretsManagementConfig.
func SecretsManagementConfigAPIToSpec(in *akuitytypes.SecretsManagementConfig) *v1alpha2.SecretsManagementConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.SecretsManagementConfig{}
	if in.Sources != nil {
		out.Sources = make([]*v1alpha2.ClusterSecretMapping, 0, len(in.Sources))
		for _, item := range in.Sources {
			out.Sources = append(out.Sources, ClusterSecretMappingAPIToSpec(item))
		}
	}
	if in.Destinations != nil {
		out.Destinations = make([]*v1alpha2.ClusterSecretMapping, 0, len(in.Destinations))
		for _, item := range in.Destinations {
			out.Destinations = append(out.Destinations, ClusterSecretMappingAPIToSpec(item))
		}
	}
	return out
}

// TargetSelectorSpecToAPI converts the curated v1alpha2 TargetSelector into the Akuity API TargetSelector wire type.
func TargetSelectorSpecToAPI(in *v1alpha2.TargetSelector) *akuitytypes.TargetSelector {
	if in == nil {
		return nil
	}
	out := &akuitytypes.TargetSelector{}
	out.ArgocdApplications = in.ArgocdApplications
	out.K8SNamespaces = in.K8SNamespaces
	out.Clusters = in.Clusters
	out.DegradedFor = in.DegradedFor
	return out
}

// TargetSelectorAPIToSpec converts the Akuity API TargetSelector wire type back into the curated v1alpha2 TargetSelector.
func TargetSelectorAPIToSpec(in *akuitytypes.TargetSelector) *v1alpha2.TargetSelector {
	if in == nil {
		return nil
	}
	out := &v1alpha2.TargetSelector{}
	out.ArgocdApplications = in.ArgocdApplications
	out.K8SNamespaces = in.K8SNamespaces
	out.Clusters = in.Clusters
	out.DegradedFor = in.DegradedFor
	return out
}
