/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/codegen. DO NOT EDIT.

package convert

import (
	v1alpha2 "github.com/akuityio/provider-crossplane-akuity/apis/core/v1alpha2"
	glue "github.com/akuityio/provider-crossplane-akuity/internal/convert/glue"
	akuitytypes "github.com/akuityio/provider-crossplane-akuity/internal/types/generated/akuity/v1alpha1"
)

// KargoAgentDataSpecToAPI converts the curated v1alpha2 KargoAgentData into the Akuity API KargoAgentData wire type.
func KargoAgentDataSpecToAPI(in *v1alpha2.KargoAgentData) *akuitytypes.KargoAgentData {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoAgentData{}
	out.Size = akuitytypes.KargoAgentSize(in.Size)
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.TargetVersion = in.TargetVersion
	out.Kustomization = glue.KustomizationStringToRaw(in.Kustomization)
	out.RemoteArgocd = in.RemoteArgocd
	out.AkuityManaged = in.AkuityManaged
	out.ArgocdNamespace = in.ArgocdNamespace
	out.SelfManagedArgocdUrl = in.SelfManagedArgocdUrl
	out.AllowedJobSa = in.AllowedJobSa
	out.MaintenanceMode = in.MaintenanceMode
	out.MaintenanceModeExpiry = in.MaintenanceModeExpiry
	out.PodInheritMetadata = in.PodInheritMetadata
	out.AutoscalerConfig = KargoAutoscalerConfigSpecToAPI(in.AutoscalerConfig)
	return out
}

// KargoAgentDataAPIToSpec converts the Akuity API KargoAgentData wire type back into the curated v1alpha2 KargoAgentData.
func KargoAgentDataAPIToSpec(in *akuitytypes.KargoAgentData) *v1alpha2.KargoAgentData {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoAgentData{}
	out.Size = v1alpha2.KargoAgentSize(in.Size)
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.TargetVersion = in.TargetVersion
	out.Kustomization = glue.KustomizationRawToString(in.Kustomization)
	out.RemoteArgocd = in.RemoteArgocd
	out.AkuityManaged = in.AkuityManaged
	out.ArgocdNamespace = in.ArgocdNamespace
	out.SelfManagedArgocdUrl = in.SelfManagedArgocdUrl
	out.AllowedJobSa = in.AllowedJobSa
	out.MaintenanceMode = in.MaintenanceMode
	out.MaintenanceModeExpiry = in.MaintenanceModeExpiry
	out.PodInheritMetadata = in.PodInheritMetadata
	out.AutoscalerConfig = KargoAutoscalerConfigAPIToSpec(in.AutoscalerConfig)
	return out
}

// KargoAgentSpecSpecToAPI converts the curated v1alpha2 KargoAgentSpec into the Akuity API KargoAgentSpec wire type.
func KargoAgentSpecSpecToAPI(in *v1alpha2.KargoAgentSpec) *akuitytypes.KargoAgentSpec {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoAgentSpec{}
	out.Description = in.Description
	out.Data = *KargoAgentDataSpecToAPI(&in.Data)
	return out
}

// KargoAgentSpecAPIToSpec converts the Akuity API KargoAgentSpec wire type back into the curated v1alpha2 KargoAgentSpec.
func KargoAgentSpecAPIToSpec(in *akuitytypes.KargoAgentSpec) *v1alpha2.KargoAgentSpec {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoAgentSpec{}
	out.Description = in.Description
	out.Data = *KargoAgentDataAPIToSpec(&in.Data)
	return out
}

// KargoAutoscalerConfigSpecToAPI converts the curated v1alpha2 KargoAutoscalerConfig into the Akuity API KargoAutoscalerConfig wire type.
func KargoAutoscalerConfigSpecToAPI(in *v1alpha2.KargoAutoscalerConfig) *akuitytypes.KargoAutoscalerConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoAutoscalerConfig{}
	out.KargoController = KargoControllerAutoScalingConfigSpecToAPI(in.KargoController)
	return out
}

// KargoAutoscalerConfigAPIToSpec converts the Akuity API KargoAutoscalerConfig wire type back into the curated v1alpha2 KargoAutoscalerConfig.
func KargoAutoscalerConfigAPIToSpec(in *akuitytypes.KargoAutoscalerConfig) *v1alpha2.KargoAutoscalerConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoAutoscalerConfig{}
	out.KargoController = KargoControllerAutoScalingConfigAPIToSpec(in.KargoController)
	return out
}

// KargoControllerAutoScalingConfigSpecToAPI converts the curated v1alpha2 KargoControllerAutoScalingConfig into the Akuity API KargoControllerAutoScalingConfig wire type.
func KargoControllerAutoScalingConfigSpecToAPI(in *v1alpha2.KargoControllerAutoScalingConfig) *akuitytypes.KargoControllerAutoScalingConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoControllerAutoScalingConfig{}
	out.ResourceMinimum = KargoResourcesSpecToAPI(in.ResourceMinimum)
	out.ResourceMaximum = KargoResourcesSpecToAPI(in.ResourceMaximum)
	return out
}

// KargoControllerAutoScalingConfigAPIToSpec converts the Akuity API KargoControllerAutoScalingConfig wire type back into the curated v1alpha2 KargoControllerAutoScalingConfig.
func KargoControllerAutoScalingConfigAPIToSpec(in *akuitytypes.KargoControllerAutoScalingConfig) *v1alpha2.KargoControllerAutoScalingConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoControllerAutoScalingConfig{}
	out.ResourceMinimum = KargoResourcesAPIToSpec(in.ResourceMinimum)
	out.ResourceMaximum = KargoResourcesAPIToSpec(in.ResourceMaximum)
	return out
}

// KargoResourcesSpecToAPI converts the curated v1alpha2 KargoResources into the Akuity API KargoResources wire type.
func KargoResourcesSpecToAPI(in *v1alpha2.KargoResources) *akuitytypes.KargoResources {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoResources{}
	out.Mem = in.Mem
	out.Cpu = in.Cpu
	return out
}

// KargoResourcesAPIToSpec converts the Akuity API KargoResources wire type back into the curated v1alpha2 KargoResources.
func KargoResourcesAPIToSpec(in *akuitytypes.KargoResources) *v1alpha2.KargoResources {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoResources{}
	out.Mem = in.Mem
	out.Cpu = in.Cpu
	return out
}
