/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/codegen. DO NOT EDIT.

package convert

import (
	v1alpha2 "github.com/akuityio/provider-crossplane-akuity/apis/core/v1alpha2"
	glue "github.com/akuityio/provider-crossplane-akuity/internal/convert/glue"
	akuitytypes "github.com/akuityio/provider-crossplane-akuity/internal/types/generated/akuity/v1alpha1"
)

// AkuityIntelligenceSpecToAPI converts the curated v1alpha2 AkuityIntelligence into the Akuity API AkuityIntelligence wire type.
func AkuityIntelligenceSpecToAPI(in *v1alpha2.AkuityIntelligence) *akuitytypes.AkuityIntelligence {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AkuityIntelligence{}
	out.AiSupportEngineerEnabled = in.AiSupportEngineerEnabled
	out.Enabled = in.Enabled
	out.AllowedUsernames = in.AllowedUsernames
	out.AllowedGroups = in.AllowedGroups
	out.ModelVersion = in.ModelVersion
	return out
}

// AkuityIntelligenceAPIToSpec converts the Akuity API AkuityIntelligence wire type back into the curated v1alpha2 AkuityIntelligence.
func AkuityIntelligenceAPIToSpec(in *akuitytypes.AkuityIntelligence) *v1alpha2.AkuityIntelligence {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AkuityIntelligence{}
	out.AiSupportEngineerEnabled = in.AiSupportEngineerEnabled
	out.Enabled = in.Enabled
	out.AllowedUsernames = in.AllowedUsernames
	out.AllowedGroups = in.AllowedGroups
	out.ModelVersion = in.ModelVersion
	return out
}

// GarbageCollectorConfigSpecToAPI converts the curated v1alpha2 GarbageCollectorConfig into the Akuity API GarbageCollectorConfig wire type.
func GarbageCollectorConfigSpecToAPI(in *v1alpha2.GarbageCollectorConfig) *akuitytypes.GarbageCollectorConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.GarbageCollectorConfig{}
	out.MaxRetainedFreight = in.MaxRetainedFreight
	out.MaxRetainedPromotions = in.MaxRetainedPromotions
	out.MinFreightDeletionAge = in.MinFreightDeletionAge
	out.MinPromotionDeletionAge = in.MinPromotionDeletionAge
	return out
}

// GarbageCollectorConfigAPIToSpec converts the Akuity API GarbageCollectorConfig wire type back into the curated v1alpha2 GarbageCollectorConfig.
func GarbageCollectorConfigAPIToSpec(in *akuitytypes.GarbageCollectorConfig) *v1alpha2.GarbageCollectorConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.GarbageCollectorConfig{}
	out.MaxRetainedFreight = in.MaxRetainedFreight
	out.MaxRetainedPromotions = in.MaxRetainedPromotions
	out.MinFreightDeletionAge = in.MinFreightDeletionAge
	out.MinPromotionDeletionAge = in.MinPromotionDeletionAge
	return out
}

// KargoAgentCustomizationSpecToAPI converts the curated v1alpha2 KargoAgentCustomization into the Akuity API KargoAgentCustomization wire type.
func KargoAgentCustomizationSpecToAPI(in *v1alpha2.KargoAgentCustomization) *akuitytypes.KargoAgentCustomization {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoAgentCustomization{}
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.Kustomization = glue.KustomizationStringToRaw(in.Kustomization)
	return out
}

// KargoAgentCustomizationAPIToSpec converts the Akuity API KargoAgentCustomization wire type back into the curated v1alpha2 KargoAgentCustomization.
func KargoAgentCustomizationAPIToSpec(in *akuitytypes.KargoAgentCustomization) *v1alpha2.KargoAgentCustomization {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoAgentCustomization{}
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.Kustomization = glue.KustomizationRawToString(in.Kustomization)
	return out
}

// KargoArgoCDUIConfigSpecToAPI converts the curated v1alpha2 KargoArgoCDUIConfig into the Akuity API KargoArgoCDUIConfig wire type.
func KargoArgoCDUIConfigSpecToAPI(in *v1alpha2.KargoArgoCDUIConfig) *akuitytypes.KargoArgoCDUIConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoArgoCDUIConfig{}
	out.IdpGroupsMapping = in.IdpGroupsMapping
	return out
}

// KargoArgoCDUIConfigAPIToSpec converts the Akuity API KargoArgoCDUIConfig wire type back into the curated v1alpha2 KargoArgoCDUIConfig.
func KargoArgoCDUIConfigAPIToSpec(in *akuitytypes.KargoArgoCDUIConfig) *v1alpha2.KargoArgoCDUIConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoArgoCDUIConfig{}
	out.IdpGroupsMapping = in.IdpGroupsMapping
	return out
}

// KargoIPAllowListEntrySpecToAPI converts the curated v1alpha2 KargoIPAllowListEntry into the Akuity API KargoIPAllowListEntry wire type.
func KargoIPAllowListEntrySpecToAPI(in *v1alpha2.KargoIPAllowListEntry) *akuitytypes.KargoIPAllowListEntry {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoIPAllowListEntry{}
	out.Ip = in.Ip
	out.Description = in.Description
	return out
}

// KargoIPAllowListEntryAPIToSpec converts the Akuity API KargoIPAllowListEntry wire type back into the curated v1alpha2 KargoIPAllowListEntry.
func KargoIPAllowListEntryAPIToSpec(in *akuitytypes.KargoIPAllowListEntry) *v1alpha2.KargoIPAllowListEntry {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoIPAllowListEntry{}
	out.Ip = in.Ip
	out.Description = in.Description
	return out
}

// KargoInstanceSpecSpecToAPI converts the curated v1alpha2 KargoInstanceSpec into the Akuity API KargoInstanceSpec wire type.
func KargoInstanceSpecSpecToAPI(in *v1alpha2.KargoInstanceSpec) *akuitytypes.KargoInstanceSpec {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoInstanceSpec{}
	out.BackendIpAllowListEnabled = in.BackendIpAllowListEnabled
	if in.IpAllowList != nil {
		out.IpAllowList = make([]*akuitytypes.KargoIPAllowListEntry, 0, len(in.IpAllowList))
		for _, item := range in.IpAllowList {
			out.IpAllowList = append(out.IpAllowList, KargoIPAllowListEntrySpecToAPI(item))
		}
	}
	out.AgentCustomizationDefaults = KargoAgentCustomizationSpecToAPI(in.AgentCustomizationDefaults)
	out.DefaultShardAgent = in.DefaultShardAgent
	out.GlobalCredentialsNs = in.GlobalCredentialsNs
	out.GlobalServiceAccountNs = in.GlobalServiceAccountNs
	out.AkuityIntelligence = AkuityIntelligenceSpecToAPI(in.AkuityIntelligence)
	out.GcConfig = GarbageCollectorConfigSpecToAPI(in.GcConfig)
	out.PromoControllerEnabled = in.PromoControllerEnabled
	out.Secrets = *SecretsManagementConfigSpecToAPI(&in.Secrets)
	out.ArgocdUi = KargoArgoCDUIConfigSpecToAPI(in.ArgocdUi)
	return out
}

// KargoInstanceSpecAPIToSpec converts the Akuity API KargoInstanceSpec wire type back into the curated v1alpha2 KargoInstanceSpec.
func KargoInstanceSpecAPIToSpec(in *akuitytypes.KargoInstanceSpec) *v1alpha2.KargoInstanceSpec {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoInstanceSpec{}
	out.BackendIpAllowListEnabled = in.BackendIpAllowListEnabled
	if in.IpAllowList != nil {
		out.IpAllowList = make([]*v1alpha2.KargoIPAllowListEntry, 0, len(in.IpAllowList))
		for _, item := range in.IpAllowList {
			out.IpAllowList = append(out.IpAllowList, KargoIPAllowListEntryAPIToSpec(item))
		}
	}
	out.AgentCustomizationDefaults = KargoAgentCustomizationAPIToSpec(in.AgentCustomizationDefaults)
	out.DefaultShardAgent = in.DefaultShardAgent
	out.GlobalCredentialsNs = in.GlobalCredentialsNs
	out.GlobalServiceAccountNs = in.GlobalServiceAccountNs
	out.AkuityIntelligence = AkuityIntelligenceAPIToSpec(in.AkuityIntelligence)
	out.GcConfig = GarbageCollectorConfigAPIToSpec(in.GcConfig)
	out.PromoControllerEnabled = in.PromoControllerEnabled
	out.Secrets = *SecretsManagementConfigAPIToSpec(&in.Secrets)
	out.ArgocdUi = KargoArgoCDUIConfigAPIToSpec(in.ArgocdUi)
	return out
}

// KargoOidcConfigSpecToAPI converts the curated v1alpha2 KargoOidcConfig into the Akuity API KargoOidcConfig wire type.
func KargoOidcConfigSpecToAPI(in *v1alpha2.KargoOidcConfig) *akuitytypes.KargoOidcConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoOidcConfig{}
	out.Enabled = in.Enabled
	out.DexEnabled = in.DexEnabled
	out.DexConfig = in.DexConfig
	if in.DexConfigSecret != nil {
		out.DexConfigSecret = make(map[string]akuitytypes.Value, len(in.DexConfigSecret))
		for k, v := range in.DexConfigSecret {
			v := v
			out.DexConfigSecret[k] = *ValueSpecToAPI(&v)
		}
	}
	out.IssuerURL = in.IssuerURL
	out.ClientID = in.ClientID
	out.CliClientID = in.CliClientID
	out.AdminAccount = *KargoPredefinedAccountDataSpecToAPI(&in.AdminAccount)
	out.ViewerAccount = *KargoPredefinedAccountDataSpecToAPI(&in.ViewerAccount)
	out.AdditionalScopes = in.AdditionalScopes
	out.UserAccount = *KargoPredefinedAccountDataSpecToAPI(&in.UserAccount)
	out.ProjectCreatorAccount = *KargoPredefinedAccountDataSpecToAPI(&in.ProjectCreatorAccount)
	return out
}

// KargoOidcConfigAPIToSpec converts the Akuity API KargoOidcConfig wire type back into the curated v1alpha2 KargoOidcConfig.
func KargoOidcConfigAPIToSpec(in *akuitytypes.KargoOidcConfig) *v1alpha2.KargoOidcConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoOidcConfig{}
	out.Enabled = in.Enabled
	out.DexEnabled = in.DexEnabled
	out.DexConfig = in.DexConfig
	if in.DexConfigSecret != nil {
		out.DexConfigSecret = make(map[string]v1alpha2.Value, len(in.DexConfigSecret))
		for k, v := range in.DexConfigSecret {
			v := v
			out.DexConfigSecret[k] = *ValueAPIToSpec(&v)
		}
	}
	out.IssuerURL = in.IssuerURL
	out.ClientID = in.ClientID
	out.CliClientID = in.CliClientID
	out.AdminAccount = *KargoPredefinedAccountDataAPIToSpec(&in.AdminAccount)
	out.ViewerAccount = *KargoPredefinedAccountDataAPIToSpec(&in.ViewerAccount)
	out.AdditionalScopes = in.AdditionalScopes
	out.UserAccount = *KargoPredefinedAccountDataAPIToSpec(&in.UserAccount)
	out.ProjectCreatorAccount = *KargoPredefinedAccountDataAPIToSpec(&in.ProjectCreatorAccount)
	return out
}

// KargoPredefinedAccountClaimValueSpecToAPI converts the curated v1alpha2 KargoPredefinedAccountClaimValue into the Akuity API KargoPredefinedAccountClaimValue wire type.
func KargoPredefinedAccountClaimValueSpecToAPI(in *v1alpha2.KargoPredefinedAccountClaimValue) *akuitytypes.KargoPredefinedAccountClaimValue {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoPredefinedAccountClaimValue{}
	out.Values = in.Values
	return out
}

// KargoPredefinedAccountClaimValueAPIToSpec converts the Akuity API KargoPredefinedAccountClaimValue wire type back into the curated v1alpha2 KargoPredefinedAccountClaimValue.
func KargoPredefinedAccountClaimValueAPIToSpec(in *akuitytypes.KargoPredefinedAccountClaimValue) *v1alpha2.KargoPredefinedAccountClaimValue {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoPredefinedAccountClaimValue{}
	out.Values = in.Values
	return out
}

// KargoPredefinedAccountDataSpecToAPI converts the curated v1alpha2 KargoPredefinedAccountData into the Akuity API KargoPredefinedAccountData wire type.
func KargoPredefinedAccountDataSpecToAPI(in *v1alpha2.KargoPredefinedAccountData) *akuitytypes.KargoPredefinedAccountData {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoPredefinedAccountData{}
	if in.Claims != nil {
		out.Claims = make(map[string]akuitytypes.KargoPredefinedAccountClaimValue, len(in.Claims))
		for k, v := range in.Claims {
			v := v
			out.Claims[k] = *KargoPredefinedAccountClaimValueSpecToAPI(&v)
		}
	}
	return out
}

// KargoPredefinedAccountDataAPIToSpec converts the Akuity API KargoPredefinedAccountData wire type back into the curated v1alpha2 KargoPredefinedAccountData.
func KargoPredefinedAccountDataAPIToSpec(in *akuitytypes.KargoPredefinedAccountData) *v1alpha2.KargoPredefinedAccountData {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoPredefinedAccountData{}
	if in.Claims != nil {
		out.Claims = make(map[string]v1alpha2.KargoPredefinedAccountClaimValue, len(in.Claims))
		for k, v := range in.Claims {
			v := v
			out.Claims[k] = *KargoPredefinedAccountClaimValueAPIToSpec(&v)
		}
	}
	return out
}

// KargoSpecSpecToAPI converts the curated v1alpha2 KargoSpec into the Akuity API KargoSpec wire type.
func KargoSpecSpecToAPI(in *v1alpha2.KargoSpec) *akuitytypes.KargoSpec {
	if in == nil {
		return nil
	}
	out := &akuitytypes.KargoSpec{}
	out.Description = in.Description
	out.Version = in.Version
	out.KargoInstanceSpec = *KargoInstanceSpecSpecToAPI(&in.KargoInstanceSpec)
	out.Fqdn = in.Fqdn
	out.Subdomain = in.Subdomain
	out.OidcConfig = KargoOidcConfigSpecToAPI(in.OidcConfig)
	return out
}

// KargoSpecAPIToSpec converts the Akuity API KargoSpec wire type back into the curated v1alpha2 KargoSpec.
func KargoSpecAPIToSpec(in *akuitytypes.KargoSpec) *v1alpha2.KargoSpec {
	if in == nil {
		return nil
	}
	out := &v1alpha2.KargoSpec{}
	out.Description = in.Description
	out.Version = in.Version
	out.KargoInstanceSpec = *KargoInstanceSpecAPIToSpec(&in.KargoInstanceSpec)
	out.Fqdn = in.Fqdn
	out.Subdomain = in.Subdomain
	out.OidcConfig = KargoOidcConfigAPIToSpec(in.OidcConfig)
	return out
}

// ValueSpecToAPI converts the curated v1alpha2 Value into the Akuity API Value wire type.
func ValueSpecToAPI(in *v1alpha2.Value) *akuitytypes.Value {
	if in == nil {
		return nil
	}
	out := &akuitytypes.Value{}
	out.Value = in.Value
	return out
}

// ValueAPIToSpec converts the Akuity API Value wire type back into the curated v1alpha2 Value.
func ValueAPIToSpec(in *akuitytypes.Value) *v1alpha2.Value {
	if in == nil {
		return nil
	}
	out := &v1alpha2.Value{}
	out.Value = in.Value
	return out
}
