/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by hack/codegen. DO NOT EDIT.

package convert

import (
	v1alpha2 "github.com/akuityio/provider-crossplane-akuity/apis/core/v1alpha2"
	glue "github.com/akuityio/provider-crossplane-akuity/internal/convert/glue"
	akuitytypes "github.com/akuityio/provider-crossplane-akuity/internal/types/generated/akuity/v1alpha1"
)

// AppControllerAutoScalingConfigSpecToAPI converts the curated v1alpha2 AppControllerAutoScalingConfig into the Akuity API AppControllerAutoScalingConfig wire type.
func AppControllerAutoScalingConfigSpecToAPI(in *v1alpha2.AppControllerAutoScalingConfig) *akuitytypes.AppControllerAutoScalingConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AppControllerAutoScalingConfig{}
	out.ResourceMinimum = ResourcesSpecToAPI(in.ResourceMinimum)
	out.ResourceMaximum = ResourcesSpecToAPI(in.ResourceMaximum)
	return out
}

// AppControllerAutoScalingConfigAPIToSpec converts the Akuity API AppControllerAutoScalingConfig wire type back into the curated v1alpha2 AppControllerAutoScalingConfig.
func AppControllerAutoScalingConfigAPIToSpec(in *akuitytypes.AppControllerAutoScalingConfig) *v1alpha2.AppControllerAutoScalingConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AppControllerAutoScalingConfig{}
	out.ResourceMinimum = ResourcesAPIToSpec(in.ResourceMinimum)
	out.ResourceMaximum = ResourcesAPIToSpec(in.ResourceMaximum)
	return out
}

// AutoScalerConfigSpecToAPI converts the curated v1alpha2 AutoScalerConfig into the Akuity API AutoScalerConfig wire type.
func AutoScalerConfigSpecToAPI(in *v1alpha2.AutoScalerConfig) *akuitytypes.AutoScalerConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.AutoScalerConfig{}
	out.ApplicationController = AppControllerAutoScalingConfigSpecToAPI(in.ApplicationController)
	out.RepoServer = RepoServerAutoScalingConfigSpecToAPI(in.RepoServer)
	return out
}

// AutoScalerConfigAPIToSpec converts the Akuity API AutoScalerConfig wire type back into the curated v1alpha2 AutoScalerConfig.
func AutoScalerConfigAPIToSpec(in *akuitytypes.AutoScalerConfig) *v1alpha2.AutoScalerConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.AutoScalerConfig{}
	out.ApplicationController = AppControllerAutoScalingConfigAPIToSpec(in.ApplicationController)
	out.RepoServer = RepoServerAutoScalingConfigAPIToSpec(in.RepoServer)
	return out
}

// ClusterArgoCDNotificationsSettingsSpecToAPI converts the curated v1alpha2 ClusterArgoCDNotificationsSettings into the Akuity API ClusterArgoCDNotificationsSettings wire type.
func ClusterArgoCDNotificationsSettingsSpecToAPI(in *v1alpha2.ClusterArgoCDNotificationsSettings) *akuitytypes.ClusterArgoCDNotificationsSettings {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ClusterArgoCDNotificationsSettings{}
	out.InClusterSettings = in.InClusterSettings
	return out
}

// ClusterArgoCDNotificationsSettingsAPIToSpec converts the Akuity API ClusterArgoCDNotificationsSettings wire type back into the curated v1alpha2 ClusterArgoCDNotificationsSettings.
func ClusterArgoCDNotificationsSettingsAPIToSpec(in *akuitytypes.ClusterArgoCDNotificationsSettings) *v1alpha2.ClusterArgoCDNotificationsSettings {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ClusterArgoCDNotificationsSettings{}
	out.InClusterSettings = in.InClusterSettings
	return out
}

// ClusterCompatibilitySpecToAPI converts the curated v1alpha2 ClusterCompatibility into the Akuity API ClusterCompatibility wire type.
func ClusterCompatibilitySpecToAPI(in *v1alpha2.ClusterCompatibility) *akuitytypes.ClusterCompatibility {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ClusterCompatibility{}
	out.Ipv6Only = in.Ipv6Only
	return out
}

// ClusterCompatibilityAPIToSpec converts the Akuity API ClusterCompatibility wire type back into the curated v1alpha2 ClusterCompatibility.
func ClusterCompatibilityAPIToSpec(in *akuitytypes.ClusterCompatibility) *v1alpha2.ClusterCompatibility {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ClusterCompatibility{}
	out.Ipv6Only = in.Ipv6Only
	return out
}

// ClusterDataSpecToAPI converts the curated v1alpha2 ClusterData into the Akuity API ClusterData wire type.
func ClusterDataSpecToAPI(in *v1alpha2.ClusterData) *akuitytypes.ClusterData {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ClusterData{}
	out.Size = akuitytypes.ClusterSize(in.Size)
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.Kustomization = glue.KustomizationStringToRaw(in.Kustomization)
	out.AppReplication = in.AppReplication
	out.TargetVersion = in.TargetVersion
	out.RedisTunneling = in.RedisTunneling
	out.DirectClusterSpec = DirectClusterSpecSpecToAPI(in.DirectClusterSpec)
	out.DatadogAnnotationsEnabled = in.DatadogAnnotationsEnabled
	out.EksAddonEnabled = in.EksAddonEnabled
	out.ManagedClusterConfig = ManagedClusterConfigSpecToAPI(in.ManagedClusterConfig)
	out.MaintenanceMode = in.MaintenanceMode
	out.MultiClusterK8SDashboardEnabled = in.MultiClusterK8SDashboardEnabled
	out.AutoscalerConfig = AutoScalerConfigSpecToAPI(in.AutoscalerConfig)
	out.Project = in.Project
	out.Compatibility = ClusterCompatibilitySpecToAPI(in.Compatibility)
	out.ArgocdNotificationsSettings = ClusterArgoCDNotificationsSettingsSpecToAPI(in.ArgocdNotificationsSettings)
	out.ServerSideDiffEnabled = in.ServerSideDiffEnabled
	out.MaintenanceModeExpiry = in.MaintenanceModeExpiry
	out.PodInheritMetadata = in.PodInheritMetadata
	return out
}

// ClusterDataAPIToSpec converts the Akuity API ClusterData wire type back into the curated v1alpha2 ClusterData.
func ClusterDataAPIToSpec(in *akuitytypes.ClusterData) *v1alpha2.ClusterData {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ClusterData{}
	out.Size = v1alpha2.ClusterSize(in.Size)
	out.AutoUpgradeDisabled = in.AutoUpgradeDisabled
	out.Kustomization = glue.KustomizationRawToString(in.Kustomization)
	out.AppReplication = in.AppReplication
	out.TargetVersion = in.TargetVersion
	out.RedisTunneling = in.RedisTunneling
	out.DirectClusterSpec = DirectClusterSpecAPIToSpec(in.DirectClusterSpec)
	out.DatadogAnnotationsEnabled = in.DatadogAnnotationsEnabled
	out.EksAddonEnabled = in.EksAddonEnabled
	out.ManagedClusterConfig = ManagedClusterConfigAPIToSpec(in.ManagedClusterConfig)
	out.MaintenanceMode = in.MaintenanceMode
	out.MultiClusterK8SDashboardEnabled = in.MultiClusterK8SDashboardEnabled
	out.AutoscalerConfig = AutoScalerConfigAPIToSpec(in.AutoscalerConfig)
	out.Project = in.Project
	out.Compatibility = ClusterCompatibilityAPIToSpec(in.Compatibility)
	out.ArgocdNotificationsSettings = ClusterArgoCDNotificationsSettingsAPIToSpec(in.ArgocdNotificationsSettings)
	out.ServerSideDiffEnabled = in.ServerSideDiffEnabled
	out.MaintenanceModeExpiry = in.MaintenanceModeExpiry
	out.PodInheritMetadata = in.PodInheritMetadata
	return out
}

// DirectClusterSpecSpecToAPI converts the curated v1alpha2 DirectClusterSpec into the Akuity API DirectClusterSpec wire type.
func DirectClusterSpecSpecToAPI(in *v1alpha2.DirectClusterSpec) *akuitytypes.DirectClusterSpec {
	if in == nil {
		return nil
	}
	out := &akuitytypes.DirectClusterSpec{}
	out.ClusterType = akuitytypes.DirectClusterType(in.ClusterType)
	out.KargoInstanceId = in.KargoInstanceId
	out.Server = in.Server
	out.Organization = in.Organization
	out.Token = in.Token
	out.CaData = in.CaData
	return out
}

// DirectClusterSpecAPIToSpec converts the Akuity API DirectClusterSpec wire type back into the curated v1alpha2 DirectClusterSpec.
func DirectClusterSpecAPIToSpec(in *akuitytypes.DirectClusterSpec) *v1alpha2.DirectClusterSpec {
	if in == nil {
		return nil
	}
	out := &v1alpha2.DirectClusterSpec{}
	out.ClusterType = v1alpha2.DirectClusterType(in.ClusterType)
	out.KargoInstanceId = in.KargoInstanceId
	out.Server = in.Server
	out.Organization = in.Organization
	out.Token = in.Token
	out.CaData = in.CaData
	return out
}

// ManagedClusterConfigSpecToAPI converts the curated v1alpha2 ManagedClusterConfig into the Akuity API ManagedClusterConfig wire type.
func ManagedClusterConfigSpecToAPI(in *v1alpha2.ManagedClusterConfig) *akuitytypes.ManagedClusterConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.ManagedClusterConfig{}
	out.SecretName = in.SecretName
	out.SecretKey = in.SecretKey
	return out
}

// ManagedClusterConfigAPIToSpec converts the Akuity API ManagedClusterConfig wire type back into the curated v1alpha2 ManagedClusterConfig.
func ManagedClusterConfigAPIToSpec(in *akuitytypes.ManagedClusterConfig) *v1alpha2.ManagedClusterConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.ManagedClusterConfig{}
	out.SecretName = in.SecretName
	out.SecretKey = in.SecretKey
	return out
}

// RepoServerAutoScalingConfigSpecToAPI converts the curated v1alpha2 RepoServerAutoScalingConfig into the Akuity API RepoServerAutoScalingConfig wire type.
func RepoServerAutoScalingConfigSpecToAPI(in *v1alpha2.RepoServerAutoScalingConfig) *akuitytypes.RepoServerAutoScalingConfig {
	if in == nil {
		return nil
	}
	out := &akuitytypes.RepoServerAutoScalingConfig{}
	out.ResourceMinimum = ResourcesSpecToAPI(in.ResourceMinimum)
	out.ResourceMaximum = ResourcesSpecToAPI(in.ResourceMaximum)
	out.ReplicaMaximum = in.ReplicaMaximum
	out.ReplicaMinimum = in.ReplicaMinimum
	return out
}

// RepoServerAutoScalingConfigAPIToSpec converts the Akuity API RepoServerAutoScalingConfig wire type back into the curated v1alpha2 RepoServerAutoScalingConfig.
func RepoServerAutoScalingConfigAPIToSpec(in *akuitytypes.RepoServerAutoScalingConfig) *v1alpha2.RepoServerAutoScalingConfig {
	if in == nil {
		return nil
	}
	out := &v1alpha2.RepoServerAutoScalingConfig{}
	out.ResourceMinimum = ResourcesAPIToSpec(in.ResourceMinimum)
	out.ResourceMaximum = ResourcesAPIToSpec(in.ResourceMaximum)
	out.ReplicaMaximum = in.ReplicaMaximum
	out.ReplicaMinimum = in.ReplicaMinimum
	return out
}

// ResourcesSpecToAPI converts the curated v1alpha2 Resources into the Akuity API Resources wire type.
func ResourcesSpecToAPI(in *v1alpha2.Resources) *akuitytypes.Resources {
	if in == nil {
		return nil
	}
	out := &akuitytypes.Resources{}
	out.Mem = in.Mem
	out.Cpu = in.Cpu
	return out
}

// ResourcesAPIToSpec converts the Akuity API Resources wire type back into the curated v1alpha2 Resources.
func ResourcesAPIToSpec(in *akuitytypes.Resources) *v1alpha2.Resources {
	if in == nil {
		return nil
	}
	out := &v1alpha2.Resources{}
	out.Mem = in.Mem
	out.Cpu = in.Cpu
	return out
}
