// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/akuityio/provider-crossplane-akuity/internal/clients/akuity (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mock_akuity_client -destination internal/clients/akuity/mock/clientset_mock.go github.com/akuityio/provider-crossplane-akuity/internal/clients/akuity Client
//

// Package mock_akuity_client is a generated GoMock package.
package mock_akuity_client

import (
	context "context"
	reflect "reflect"

	argocdv1 "github.com/akuity/api-client-go/pkg/api/gen/argocd/v1"
	v1alpha1 "github.com/akuityio/provider-crossplane-akuity/apis/core/v1alpha1"
	v1alpha10 "github.com/akuityio/provider-crossplane-akuity/internal/types/generated/akuity/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ApplyCluster mocks base method.
func (m *MockClient) ApplyCluster(arg0 context.Context, arg1 string, arg2 v1alpha10.Cluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCluster", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyCluster indicates an expected call of ApplyCluster.
func (mr *MockClientMockRecorder) ApplyCluster(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCluster", reflect.TypeOf((*MockClient)(nil).ApplyCluster), arg0, arg1, arg2)
}

// ApplyInstance mocks base method.
func (m *MockClient) ApplyInstance(arg0 context.Context, arg1 *argocdv1.ApplyInstanceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyInstance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyInstance indicates an expected call of ApplyInstance.
func (mr *MockClientMockRecorder) ApplyInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyInstance", reflect.TypeOf((*MockClient)(nil).ApplyInstance), arg0, arg1)
}

// BuildApplyInstanceRequest mocks base method.
func (m *MockClient) BuildApplyInstanceRequest(arg0 v1alpha1.Instance) (*argocdv1.ApplyInstanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildApplyInstanceRequest", arg0)
	ret0, _ := ret[0].(*argocdv1.ApplyInstanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildApplyInstanceRequest indicates an expected call of BuildApplyInstanceRequest.
func (mr *MockClientMockRecorder) BuildApplyInstanceRequest(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildApplyInstanceRequest", reflect.TypeOf((*MockClient)(nil).BuildApplyInstanceRequest), arg0)
}

// DeleteCluster mocks base method.
func (m *MockClient) DeleteCluster(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockClientMockRecorder) DeleteCluster(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockClient)(nil).DeleteCluster), arg0, arg1, arg2)
}

// DeleteInstance mocks base method.
func (m *MockClient) DeleteInstance(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockClientMockRecorder) DeleteInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockClient)(nil).DeleteInstance), arg0, arg1)
}

// ExportInstance mocks base method.
func (m *MockClient) ExportInstance(arg0 context.Context, arg1 string) (*argocdv1.ExportInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportInstance", arg0, arg1)
	ret0, _ := ret[0].(*argocdv1.ExportInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportInstance indicates an expected call of ExportInstance.
func (mr *MockClientMockRecorder) ExportInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportInstance", reflect.TypeOf((*MockClient)(nil).ExportInstance), arg0, arg1)
}

// GetCluster mocks base method.
func (m *MockClient) GetCluster(arg0 context.Context, arg1, arg2 string) (*argocdv1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", arg0, arg1, arg2)
	ret0, _ := ret[0].(*argocdv1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockClientMockRecorder) GetCluster(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockClient)(nil).GetCluster), arg0, arg1, arg2)
}

// GetClusterManifests mocks base method.
func (m *MockClient) GetClusterManifests(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterManifests", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterManifests indicates an expected call of GetClusterManifests.
func (mr *MockClientMockRecorder) GetClusterManifests(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterManifests", reflect.TypeOf((*MockClient)(nil).GetClusterManifests), arg0, arg1, arg2)
}

// GetInstance mocks base method.
func (m *MockClient) GetInstance(arg0 context.Context, arg1 string) (*argocdv1.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", arg0, arg1)
	ret0, _ := ret[0].(*argocdv1.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockClientMockRecorder) GetInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockClient)(nil).GetInstance), arg0, arg1)
}
