// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/akuity/api-client-go/pkg/api/gen/kargo/v1 (interfaces: KargoServiceGatewayClient)
//
// Generated by this command:
//
//	mockgen -package mock_akuity_client -destination internal/clients/akuity/mock/kargo_service_gateway_client_mock.go github.com/akuity/api-client-go/pkg/api/gen/kargo/v1 KargoServiceGatewayClient
//

// Package mock_akuity_client is a generated GoMock package.
package mock_akuity_client

import (
	context "context"
	reflect "reflect"

	kargov1 "github.com/akuity/api-client-go/pkg/api/gen/kargo/v1"
	gomock "go.uber.org/mock/gomock"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
)

// MockKargoServiceGatewayClient is a mock of KargoServiceGatewayClient interface.
type MockKargoServiceGatewayClient struct {
	ctrl     *gomock.Controller
	recorder *MockKargoServiceGatewayClientMockRecorder
	isgomock struct{}
}

// MockKargoServiceGatewayClientMockRecorder is the mock recorder for MockKargoServiceGatewayClient.
type MockKargoServiceGatewayClientMockRecorder struct {
	mock *MockKargoServiceGatewayClient
}

// NewMockKargoServiceGatewayClient creates a new mock instance.
func NewMockKargoServiceGatewayClient(ctrl *gomock.Controller) *MockKargoServiceGatewayClient {
	mock := &MockKargoServiceGatewayClient{ctrl: ctrl}
	mock.recorder = &MockKargoServiceGatewayClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKargoServiceGatewayClient) EXPECT() *MockKargoServiceGatewayClientMockRecorder {
	return m.recorder
}

// ApplyKargoInstance mocks base method.
func (m *MockKargoServiceGatewayClient) ApplyKargoInstance(arg0 context.Context, arg1 *kargov1.ApplyKargoInstanceRequest) (*kargov1.ApplyKargoInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyKargoInstance", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.ApplyKargoInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyKargoInstance indicates an expected call of ApplyKargoInstance.
func (mr *MockKargoServiceGatewayClientMockRecorder) ApplyKargoInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyKargoInstance", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).ApplyKargoInstance), arg0, arg1)
}

// CreateKargoInstance mocks base method.
func (m *MockKargoServiceGatewayClient) CreateKargoInstance(arg0 context.Context, arg1 *kargov1.CreateKargoInstanceRequest) (*kargov1.CreateKargoInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKargoInstance", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.CreateKargoInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKargoInstance indicates an expected call of CreateKargoInstance.
func (mr *MockKargoServiceGatewayClientMockRecorder) CreateKargoInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKargoInstance", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).CreateKargoInstance), arg0, arg1)
}

// CreateKargoInstanceAgent mocks base method.
func (m *MockKargoServiceGatewayClient) CreateKargoInstanceAgent(arg0 context.Context, arg1 *kargov1.CreateKargoInstanceAgentRequest) (*kargov1.CreateKargoInstanceAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKargoInstanceAgent", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.CreateKargoInstanceAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKargoInstanceAgent indicates an expected call of CreateKargoInstanceAgent.
func (mr *MockKargoServiceGatewayClientMockRecorder) CreateKargoInstanceAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKargoInstanceAgent", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).CreateKargoInstanceAgent), arg0, arg1)
}

// DeleteInstance mocks base method.
func (m *MockKargoServiceGatewayClient) DeleteInstance(arg0 context.Context, arg1 *kargov1.DeleteInstanceRequest) (*kargov1.DeleteInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.DeleteInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockKargoServiceGatewayClientMockRecorder) DeleteInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).DeleteInstance), arg0, arg1)
}

// DeleteInstanceAgent mocks base method.
func (m *MockKargoServiceGatewayClient) DeleteInstanceAgent(arg0 context.Context, arg1 *kargov1.DeleteInstanceAgentRequest) (*kargov1.DeleteInstanceAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstanceAgent", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.DeleteInstanceAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstanceAgent indicates an expected call of DeleteInstanceAgent.
func (mr *MockKargoServiceGatewayClientMockRecorder) DeleteInstanceAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceAgent", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).DeleteInstanceAgent), arg0, arg1)
}

// ExportKargoInstance mocks base method.
func (m *MockKargoServiceGatewayClient) ExportKargoInstance(arg0 context.Context, arg1 *kargov1.ExportKargoInstanceRequest) (*kargov1.ExportKargoInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportKargoInstance", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.ExportKargoInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportKargoInstance indicates an expected call of ExportKargoInstance.
func (mr *MockKargoServiceGatewayClientMockRecorder) ExportKargoInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportKargoInstance", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).ExportKargoInstance), arg0, arg1)
}

// GetInstanceAgentCommand mocks base method.
func (m *MockKargoServiceGatewayClient) GetInstanceAgentCommand(arg0 context.Context, arg1 *kargov1.GetInstanceAgentCommandRequest) (*kargov1.GetInstanceAgentCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceAgentCommand", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.GetInstanceAgentCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceAgentCommand indicates an expected call of GetInstanceAgentCommand.
func (mr *MockKargoServiceGatewayClientMockRecorder) GetInstanceAgentCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceAgentCommand", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).GetInstanceAgentCommand), arg0, arg1)
}

// GetKargoInstance mocks base method.
func (m *MockKargoServiceGatewayClient) GetKargoInstance(arg0 context.Context, arg1 *kargov1.GetKargoInstanceRequest) (*kargov1.GetKargoInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKargoInstance", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.GetKargoInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKargoInstance indicates an expected call of GetKargoInstance.
func (mr *MockKargoServiceGatewayClientMockRecorder) GetKargoInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKargoInstance", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).GetKargoInstance), arg0, arg1)
}

// GetKargoInstanceAgent mocks base method.
func (m *MockKargoServiceGatewayClient) GetKargoInstanceAgent(arg0 context.Context, arg1 *kargov1.GetKargoInstanceAgentRequest) (*kargov1.GetKargoInstanceAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKargoInstanceAgent", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.GetKargoInstanceAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKargoInstanceAgent indicates an expected call of GetKargoInstanceAgent.
func (mr *MockKargoServiceGatewayClientMockRecorder) GetKargoInstanceAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKargoInstanceAgent", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).GetKargoInstanceAgent), arg0, arg1)
}

// GetKargoInstanceAgentManifests mocks base method.
func (m *MockKargoServiceGatewayClient) GetKargoInstanceAgentManifests(arg0 context.Context, arg1 *kargov1.GetKargoInstanceAgentManifestsRequest) (<-chan *httpbody.HttpBody, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKargoInstanceAgentManifests", arg0, arg1)
	ret0, _ := ret[0].(<-chan *httpbody.HttpBody)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetKargoInstanceAgentManifests indicates an expected call of GetKargoInstanceAgentManifests.
func (mr *MockKargoServiceGatewayClientMockRecorder) GetKargoInstanceAgentManifests(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKargoInstanceAgentManifests", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).GetKargoInstanceAgentManifests), arg0, arg1)
}

// GetPromotionEvents mocks base method.
func (m *MockKargoServiceGatewayClient) GetPromotionEvents(arg0 context.Context, arg1 *kargov1.GetPromotionEventsRequest) (*kargov1.GetPromotionEventsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotionEvents", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.GetPromotionEventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotionEvents indicates an expected call of GetPromotionEvents.
func (mr *MockKargoServiceGatewayClientMockRecorder) GetPromotionEvents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotionEvents", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).GetPromotionEvents), arg0, arg1)
}

// GetPromotionStats mocks base method.
func (m *MockKargoServiceGatewayClient) GetPromotionStats(arg0 context.Context, arg1 *kargov1.GetPromotionStatsRequest) (*kargov1.GetPromotionStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotionStats", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.GetPromotionStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotionStats indicates an expected call of GetPromotionStats.
func (mr *MockKargoServiceGatewayClientMockRecorder) GetPromotionStats(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotionStats", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).GetPromotionStats), arg0, arg1)
}

// GetStageSpecificStats mocks base method.
func (m *MockKargoServiceGatewayClient) GetStageSpecificStats(arg0 context.Context, arg1 *kargov1.GetStageSpecificStatsRequest) (*kargov1.GetStageSpecificStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStageSpecificStats", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.GetStageSpecificStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStageSpecificStats indicates an expected call of GetStageSpecificStats.
func (mr *MockKargoServiceGatewayClientMockRecorder) GetStageSpecificStats(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStageSpecificStats", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).GetStageSpecificStats), arg0, arg1)
}

// ListKargoInstanceAgents mocks base method.
func (m *MockKargoServiceGatewayClient) ListKargoInstanceAgents(arg0 context.Context, arg1 *kargov1.ListKargoInstanceAgentsRequest) (*kargov1.ListKargoInstanceAgentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKargoInstanceAgents", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.ListKargoInstanceAgentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKargoInstanceAgents indicates an expected call of ListKargoInstanceAgents.
func (mr *MockKargoServiceGatewayClientMockRecorder) ListKargoInstanceAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKargoInstanceAgents", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).ListKargoInstanceAgents), arg0, arg1)
}

// ListKargoInstances mocks base method.
func (m *MockKargoServiceGatewayClient) ListKargoInstances(arg0 context.Context, arg1 *kargov1.ListKargoInstancesRequest) (*kargov1.ListKargoInstancesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKargoInstances", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.ListKargoInstancesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKargoInstances indicates an expected call of ListKargoInstances.
func (mr *MockKargoServiceGatewayClientMockRecorder) ListKargoInstances(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKargoInstances", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).ListKargoInstances), arg0, arg1)
}

// PatchKargoInstance mocks base method.
func (m *MockKargoServiceGatewayClient) PatchKargoInstance(arg0 context.Context, arg1 *kargov1.PatchKargoInstanceRequest) (*kargov1.PatchKargoInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchKargoInstance", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.PatchKargoInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchKargoInstance indicates an expected call of PatchKargoInstance.
func (mr *MockKargoServiceGatewayClientMockRecorder) PatchKargoInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchKargoInstance", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).PatchKargoInstance), arg0, arg1)
}

// RotateInstanceAgentCredentials mocks base method.
func (m *MockKargoServiceGatewayClient) RotateInstanceAgentCredentials(arg0 context.Context, arg1 *kargov1.RotateInstanceAgentCredentialsRequest) (*kargov1.RotateInstanceAgentCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateInstanceAgentCredentials", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.RotateInstanceAgentCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateInstanceAgentCredentials indicates an expected call of RotateInstanceAgentCredentials.
func (mr *MockKargoServiceGatewayClientMockRecorder) RotateInstanceAgentCredentials(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateInstanceAgentCredentials", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).RotateInstanceAgentCredentials), arg0, arg1)
}

// UpdateInstanceAgentVersion mocks base method.
func (m *MockKargoServiceGatewayClient) UpdateInstanceAgentVersion(arg0 context.Context, arg1 *kargov1.UpdateInstanceAgentVersionRequest) (*kargov1.UpdateInstanceAgentVersionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceAgentVersion", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.UpdateInstanceAgentVersionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstanceAgentVersion indicates an expected call of UpdateInstanceAgentVersion.
func (mr *MockKargoServiceGatewayClientMockRecorder) UpdateInstanceAgentVersion(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceAgentVersion", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).UpdateInstanceAgentVersion), arg0, arg1)
}

// UpdateKargoInstanceAgent mocks base method.
func (m *MockKargoServiceGatewayClient) UpdateKargoInstanceAgent(arg0 context.Context, arg1 *kargov1.UpdateKargoInstanceAgentRequest) (*kargov1.UpdateKargoInstanceAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKargoInstanceAgent", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.UpdateKargoInstanceAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKargoInstanceAgent indicates an expected call of UpdateKargoInstanceAgent.
func (mr *MockKargoServiceGatewayClientMockRecorder) UpdateKargoInstanceAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKargoInstanceAgent", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).UpdateKargoInstanceAgent), arg0, arg1)
}

// UpdateKargoInstanceAgents mocks base method.
func (m *MockKargoServiceGatewayClient) UpdateKargoInstanceAgents(arg0 context.Context, arg1 *kargov1.UpdateKargoInstanceAgentsRequest) (*kargov1.UpdateKargoInstanceAgentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKargoInstanceAgents", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.UpdateKargoInstanceAgentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKargoInstanceAgents indicates an expected call of UpdateKargoInstanceAgents.
func (mr *MockKargoServiceGatewayClientMockRecorder) UpdateKargoInstanceAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKargoInstanceAgents", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).UpdateKargoInstanceAgents), arg0, arg1)
}

// UpdateKargoInstanceWorkspace mocks base method.
func (m *MockKargoServiceGatewayClient) UpdateKargoInstanceWorkspace(arg0 context.Context, arg1 *kargov1.UpdateKargoInstanceWorkspaceRequest) (*kargov1.UpdateKargoInstanceWorkspaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKargoInstanceWorkspace", arg0, arg1)
	ret0, _ := ret[0].(*kargov1.UpdateKargoInstanceWorkspaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKargoInstanceWorkspace indicates an expected call of UpdateKargoInstanceWorkspace.
func (mr *MockKargoServiceGatewayClientMockRecorder) UpdateKargoInstanceWorkspace(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKargoInstanceWorkspace", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).UpdateKargoInstanceWorkspace), arg0, arg1)
}

// WatchKargoInstanceAgents mocks base method.
func (m *MockKargoServiceGatewayClient) WatchKargoInstanceAgents(arg0 context.Context, arg1 *kargov1.WatchKargoInstanceAgentsRequest) (<-chan *kargov1.WatchKargoInstanceAgentsResponse, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchKargoInstanceAgents", arg0, arg1)
	ret0, _ := ret[0].(<-chan *kargov1.WatchKargoInstanceAgentsResponse)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WatchKargoInstanceAgents indicates an expected call of WatchKargoInstanceAgents.
func (mr *MockKargoServiceGatewayClientMockRecorder) WatchKargoInstanceAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchKargoInstanceAgents", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).WatchKargoInstanceAgents), arg0, arg1)
}

// WatchKargoInstances mocks base method.
func (m *MockKargoServiceGatewayClient) WatchKargoInstances(arg0 context.Context, arg1 *kargov1.WatchKargoInstancesRequest) (<-chan *kargov1.WatchKargoInstancesResponse, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchKargoInstances", arg0, arg1)
	ret0, _ := ret[0].(<-chan *kargov1.WatchKargoInstancesResponse)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WatchKargoInstances indicates an expected call of WatchKargoInstances.
func (mr *MockKargoServiceGatewayClientMockRecorder) WatchKargoInstances(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchKargoInstances", reflect.TypeOf((*MockKargoServiceGatewayClient)(nil).WatchKargoInstances), arg0, arg1)
}
