// Code generated by gencrossplanetypes. DO NOT EDIT.
//
// This file is generated from the upstream Akuity API wire types and
// transcluded into the v1alpha2 package so hand-authored shells in
// provider-crossplane-akuity's apis/core/v1alpha2 can reference the
// leaves directly without crossing a package boundary.
//
// ============================================================
// MANUAL ADDITIONS — guard against accidental loss on regen
// ============================================================
// gencrossplanetypes in akuity-platform owns this file's contents, but
// a small set of provider-crossplane-akuity-specific fields and
// kubebuilder markers has been added by hand because upstream has no
// corresponding concept:
//
//   - KargoOidcConfig.DexConfigSecretRef (*xpv1.LocalSecretReference)
//     Nested same-namespace Secret reference for dex credentials. The
//     controller resolves it at reconcile time and injects the wire-
//     shape Value map; plaintext never lives on the managed resource
//     spec.
//
//   - KargoOidcConfig.{Enabled,DexEnabled,DexConfig,DexConfigSecret,
//     IssuerURL,ClientID,CliClientID,AdminAccount,ViewerAccount,
//     AdditionalScopes,UserAccount,ProjectCreatorAccount}
//     Tagged with `// +optional` so controller-gen drops them from the
//     CRD's `required` array. Upstream emits these without omitempty
//     on every field, which made the generated CRD reject perfectly
//     valid ref-only OIDC manifests at admission time. The wire shape
//     is unchanged; only the OpenAPI schema is relaxed.
//
// A guard test in zz_generated_wire_guard_test.go fails CI if any of
// these additions disappear after a sync from upstream. When that
// fires, the correct fix is to re-add the missing pieces here AND
// either (a) land the upstream overlay feature tracked as Follow-up Z
// in PARITY_PLAN.md so future syncs stop clobbering them, or (b) mirror
// the additions into the upstream generator's emission path.
// ============================================================

package v1alpha2

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type ArgoCDSpec struct {
	Description  string             `json:"description"`
	Version      string             `json:"version"`
	Shard        string             `json:"shard"`
	InstanceSpec ArgoCDInstanceSpec `json:"instanceSpec,omitempty"`
}

type ArgoCDExtensionInstallEntry struct {
	Id      string `json:"id,omitempty"`
	Version string `json:"version,omitempty"`
}

type ClusterCustomization struct {
	AutoUpgradeDisabled   *bool  `json:"autoUpgradeDisabled,omitempty"`
	Kustomization         string `json:"kustomization,omitempty"`
	AppReplication        *bool  `json:"appReplication,omitempty"`
	RedisTunneling        *bool  `json:"redisTunneling,omitempty"`
	ServerSideDiffEnabled *bool  `json:"serverSideDiffEnabled,omitempty"`
}

type AppsetPolicy struct {
	Policy         string `json:"policy,omitempty"`
	OverridePolicy *bool  `json:"overridePolicy,omitempty"`
}

type AgentPermissionsRule struct {
	ApiGroups []string `json:"apiGroups,omitempty"`
	Resources []string `json:"resources,omitempty"`
	Verbs     []string `json:"verbs,omitempty"`
}

type CrossplaneExtensionResource struct {
	Group string `json:"group,omitempty"`
}

type CrossplaneExtension struct {
	Resources []*CrossplaneExtensionResource `json:"resources,omitempty"`
}

type AkuityIntelligenceExtension struct {
	Enabled                  *bool    `json:"enabled,omitempty"`
	AllowedUsernames         []string `json:"allowedUsernames,omitempty"`
	AllowedGroups            []string `json:"allowedGroups,omitempty"`
	AiSupportEngineerEnabled *bool    `json:"aiSupportEngineerEnabled,omitempty"`
	ModelVersion             string   `json:"modelVersion,omitempty"`
}

type ClusterAddonsExtension struct {
	Enabled          *bool    `json:"enabled,omitempty"`
	AllowedUsernames []string `json:"allowedUsernames,omitempty"`
	AllowedGroups    []string `json:"allowedGroups,omitempty"`
}

type TargetSelector struct {
	ArgocdApplications []string `json:"argocdApplications,omitempty"`
	K8SNamespaces      []string `json:"k8sNamespaces,omitempty"`
	Clusters           []string `json:"clusters,omitempty"`
	DegradedFor        *string  `json:"degradedFor,omitempty"`
}

type Runbook struct {
	Name              string          `json:"name,omitempty"`
	Content           string          `json:"content,omitempty"`
	AppliedTo         *TargetSelector `json:"appliedTo,omitempty"`
	SlackChannelNames []string        `json:"slackChannelNames,omitempty"`
}

type IncidentWebhookConfig struct {
	Name                           string `json:"name,omitempty"`
	DescriptionPath                string `json:"descriptionPath,omitempty"`
	ClusterPath                    string `json:"clusterPath,omitempty"`
	K8SNamespacePath               string `json:"k8sNamespacePath,omitempty"`
	ArgocdApplicationNamePath      string `json:"argocdApplicationNamePath,omitempty"`
	ArgocdApplicationNamespacePath string `json:"argocdApplicationNamespacePath,omitempty"`
	TitlePath                      string `json:"titlePath,omitempty"`
}

type IncidentsGroupingConfig struct {
	K8SNamespaces          []string `json:"k8sNamespaces,omitempty"`
	ArgocdApplicationNames []string `json:"argocdApplicationNames,omitempty"`
}

type IncidentInvestigationApprovalScope struct {
	ArgocdApplications      []string `json:"argocdApplications,omitempty"`
	K8SNamespaces           []string `json:"k8sNamespaces,omitempty"`
	Clusters                []string `json:"clusters,omitempty"`
	ConsecutiveAutoClosures int32    `json:"consecutiveAutoClosures,omitempty"`
}

type IncidentInvestigationApprovalConfig struct {
	Scopes []*IncidentInvestigationApprovalScope `json:"scopes,omitempty"`
}

type IncidentsConfig struct {
	Triggers              []*TargetSelector                    `json:"triggers,omitempty"`
	Webhooks              []*IncidentWebhookConfig             `json:"webhooks,omitempty"`
	Grouping              *IncidentsGroupingConfig             `json:"grouping,omitempty"`
	InvestigationApproval *IncidentInvestigationApprovalConfig `json:"investigationApproval,omitempty"`
}

type RunbookRepo struct {
	RepoUrl    string                     `json:"repoUrl,omitempty"`
	Revision   *string                    `json:"revision,omitempty"`
	Path       *string                    `json:"path,omitempty"`
	AppliedFor map[string]*TargetSelector `json:"appliedFor,omitempty"`
}

type AIConfig struct {
	Runbooks            []*Runbook       `json:"runbooks,omitempty"`
	Incidents           *IncidentsConfig `json:"incidents,omitempty"`
	ArgocdSlackService  *string          `json:"argocdSlackService,omitempty"`
	ArgocdSlackChannels []string         `json:"argocdSlackChannels,omitempty"`
	RunbookRepos        []*RunbookRepo   `json:"runbookRepos,omitempty"`
}

type AdditionalAttributeRule struct {
	Group       string   `json:"group,omitempty"`
	Kind        string   `json:"kind,omitempty"`
	Annotations []string `json:"annotations,omitempty"`
	Labels      []string `json:"labels,omitempty"`
	Namespace   string   `json:"namespace,omitempty"`
}

type KubeVisionConfig struct {
	CveScanConfig        *CveScanConfig             `json:"cveScanConfig,omitempty"`
	AiConfig             *AIConfig                  `json:"aiConfig,omitempty"`
	AdditionalAttributes []*AdditionalAttributeRule `json:"additionalAttributes,omitempty"`
}

type AppInAnyNamespaceConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

type CustomDeprecatedAPI struct {
	ApiVersion                     string `json:"apiVersion,omitempty"`
	NewApiVersion                  string `json:"newApiVersion,omitempty"`
	DeprecatedInKubernetesVersion  string `json:"deprecatedInKubernetesVersion,omitempty"`
	UnavailableInKubernetesVersion string `json:"unavailableInKubernetesVersion,omitempty"`
}

type CveScanConfig struct {
	ScanEnabled    *bool  `json:"scanEnabled,omitempty"`
	RescanInterval string `json:"rescanInterval,omitempty"`
}

type ObjectSelector struct {
	MatchLabels      map[string]string           `json:"matchLabels,omitempty"`
	MatchExpressions []*LabelSelectorRequirement `json:"matchExpressions,omitempty"`
}

type LabelSelectorRequirement struct {
	Key      *string  `json:"key,omitempty"`
	Operator *string  `json:"operator,omitempty"`
	Values   []string `json:"values,omitempty"`
}

type ClusterSecretMapping struct {
	Clusters *ObjectSelector `json:"clusters,omitempty"`
	Secrets  *ObjectSelector `json:"secrets,omitempty"`
}

type SecretsManagementConfig struct {
	Sources      []*ClusterSecretMapping `json:"sources,omitempty"`
	Destinations []*ClusterSecretMapping `json:"destinations,omitempty"`
}

type ApplicationSetExtension struct {
	Enabled *bool `json:"enabled,omitempty"`
}

type BucketRateLimiting struct {
	Enabled    *bool  `json:"enabled,omitempty"`
	BucketSize uint32 `json:"bucketSize,omitempty"`
	BucketQps  uint32 `json:"bucketQps,omitempty"`
}

type ItemRateLimiting struct {
	Enabled         *bool   `json:"enabled,omitempty"`
	FailureCooldown uint32  `json:"failureCooldown,omitempty"`
	BaseDelay       uint32  `json:"baseDelay,omitempty"`
	MaxDelay        uint32  `json:"maxDelay,omitempty"`
	BackoffFactor   float32 `json:"backoffFactor,omitempty"`
}

type AppReconciliationsRateLimiting struct {
	BucketRateLimiting *BucketRateLimiting `json:"bucketRateLimiting,omitempty"`
	ItemRateLimiting   *ItemRateLimiting   `json:"itemRateLimiting,omitempty"`
}

type ConfigManagementToolVersions struct {
	DefaultVersion     string   `json:"defaultVersion,omitempty"`
	AdditionalVersions []string `json:"additionalVersions,omitempty"`
}

type ManifestGeneration struct {
	Kustomize *ConfigManagementToolVersions `json:"kustomize,omitempty"`
}

type ArgoCDInstanceSpec struct {
	IpAllowList                     []*IPAllowListEntry             `json:"ipAllowList,omitempty"`
	Subdomain                       string                          `json:"subdomain,omitempty"`
	DeclarativeManagementEnabled    *bool                           `json:"declarativeManagementEnabled,omitempty"`
	Extensions                      []*ArgoCDExtensionInstallEntry  `json:"extensions,omitempty"`
	ClusterCustomizationDefaults    *ClusterCustomization           `json:"clusterCustomizationDefaults,omitempty"`
	ImageUpdaterEnabled             *bool                           `json:"imageUpdaterEnabled,omitempty"`
	BackendIpAllowListEnabled       *bool                           `json:"backendIpAllowListEnabled,omitempty"`
	RepoServerDelegate              *RepoServerDelegate             `json:"repoServerDelegate,omitempty"`
	AuditExtensionEnabled           *bool                           `json:"auditExtensionEnabled,omitempty"`
	SyncHistoryExtensionEnabled     *bool                           `json:"syncHistoryExtensionEnabled,omitempty"`
	CrossplaneExtension             *CrossplaneExtension            `json:"crossplaneExtension,omitempty"`
	ImageUpdaterDelegate            *ImageUpdaterDelegate           `json:"imageUpdaterDelegate,omitempty"`
	AppSetDelegate                  *AppSetDelegate                 `json:"appSetDelegate,omitempty"`
	AssistantExtensionEnabled       *bool                           `json:"assistantExtensionEnabled,omitempty"`
	AppsetPolicy                    *AppsetPolicy                   `json:"appsetPolicy,omitempty"`
	HostAliases                     []*HostAliases                  `json:"hostAliases,omitempty"`
	AgentPermissionsRules           []*AgentPermissionsRule         `json:"agentPermissionsRules,omitempty"`
	Fqdn                            string                          `json:"fqdn,omitempty"`
	MultiClusterK8SDashboardEnabled *bool                           `json:"multiClusterK8sDashboardEnabled,omitempty"`
	AkuityIntelligenceExtension     *AkuityIntelligenceExtension    `json:"akuityIntelligenceExtension,omitempty"`
	ImageUpdaterVersion             string                          `json:"imageUpdaterVersion,omitempty"`
	CustomDeprecatedApis            []*CustomDeprecatedAPI          `json:"customDeprecatedApis,omitempty"`
	KubeVisionConfig                *KubeVisionConfig               `json:"kubeVisionConfig,omitempty"`
	AppInAnyNamespaceConfig         *AppInAnyNamespaceConfig        `json:"appInAnyNamespaceConfig,omitempty"`
	Basepath                        string                          `json:"basepath,omitempty"`
	AppsetProgressiveSyncsEnabled   *bool                           `json:"appsetProgressiveSyncsEnabled,omitempty"`
	Secrets                         *SecretsManagementConfig        `json:"secrets,omitempty"`
	AppsetPlugins                   []*AppsetPlugins                `json:"appsetPlugins,omitempty"`
	ApplicationSetExtension         *ApplicationSetExtension        `json:"applicationSetExtension,omitempty"`
	AppReconciliationsRateLimiting  *AppReconciliationsRateLimiting `json:"appReconciliationsRateLimiting,omitempty"`
	MetricsIngressUsername          *string                         `json:"metricsIngressUsername,omitempty"`
	MetricsIngressPasswordHash      *string                         `json:"metricsIngressPasswordHash,omitempty"`
	PrivilegedNotificationCluster   *string                         `json:"privilegedNotificationCluster,omitempty"`
	ClusterAddonsExtension          *ClusterAddonsExtension         `json:"clusterAddonsExtension,omitempty"`
	ManifestGeneration              *ManifestGeneration             `json:"manifestGeneration,omitempty"`
}

type AppsetPlugins struct {
	Name           string `json:"name,omitempty"`
	Token          string `json:"token,omitempty"`
	BaseUrl        string `json:"baseUrl,omitempty"`
	RequestTimeout int32  `json:"requestTimeout,omitempty"`
}

type ManagedCluster struct {
	ClusterName string `json:"clusterName,omitempty"`
}

type RepoServerDelegate struct {
	ControlPlane   *bool           `json:"controlPlane,omitempty"`
	ManagedCluster *ManagedCluster `json:"managedCluster,omitempty"`
}

type ImageUpdaterDelegate struct {
	ControlPlane   *bool           `json:"controlPlane,omitempty"`
	ManagedCluster *ManagedCluster `json:"managedCluster,omitempty"`
}

type AppSetDelegate struct {
	ManagedCluster *ManagedCluster `json:"managedCluster,omitempty"`
}

type IPAllowListEntry struct {
	Ip          string `json:"ip,omitempty"`
	Description string `json:"description,omitempty"`
}

type HostAliases struct {
	Ip        string   `json:"ip,omitempty"`
	Hostnames []string `json:"hostnames,omitempty"`
}

type ClusterSize string

type DirectClusterType string

type Resources struct {
	Mem string `json:"mem,omitempty"`
	Cpu string `json:"cpu,omitempty"`
}

type DirectClusterSpec struct {
	ClusterType     DirectClusterType `json:"clusterType,omitempty"`
	KargoInstanceId *string           `json:"kargoInstanceId,omitempty"`
	Server          *string           `json:"server,omitempty"`
	Organization    *string           `json:"organization,omitempty"`
	Token           *string           `json:"token,omitempty"`
	CaData          *string           `json:"caData,omitempty"`
}

type ManagedClusterConfig struct {
	SecretName string `json:"secretName,omitempty"`
	SecretKey  string `json:"secretKey,omitempty"`
}

type AutoScalerConfig struct {
	ApplicationController *AppControllerAutoScalingConfig `json:"applicationController,omitempty"`
	RepoServer            *RepoServerAutoScalingConfig    `json:"repoServer,omitempty"`
}

type AppControllerAutoScalingConfig struct {
	ResourceMinimum *Resources `json:"resourceMinimum,omitempty"`
	ResourceMaximum *Resources `json:"resourceMaximum,omitempty"`
}

type RepoServerAutoScalingConfig struct {
	ResourceMinimum *Resources `json:"resourceMinimum,omitempty"`
	ResourceMaximum *Resources `json:"resourceMaximum,omitempty"`
	ReplicaMaximum  int32      `json:"replicaMaximum,omitempty"`
	ReplicaMinimum  int32      `json:"replicaMinimum,omitempty"`
}

type ClusterCompatibility struct {
	Ipv6Only *bool `json:"ipv6Only,omitempty"`
}

type ClusterArgoCDNotificationsSettings struct {
	InClusterSettings *bool `json:"inClusterSettings,omitempty"`
}

type ClusterData struct {
	Size                            ClusterSize                         `json:"size,omitempty"`
	AutoUpgradeDisabled             *bool                               `json:"autoUpgradeDisabled,omitempty"`
	Kustomization                   string                              `json:"kustomization,omitempty"`
	AppReplication                  *bool                               `json:"appReplication,omitempty"`
	TargetVersion                   string                              `json:"targetVersion,omitempty"`
	RedisTunneling                  *bool                               `json:"redisTunneling,omitempty"`
	DirectClusterSpec               *DirectClusterSpec                  `json:"directClusterSpec,omitempty"`
	DatadogAnnotationsEnabled       *bool                               `json:"datadogAnnotationsEnabled,omitempty"`
	EksAddonEnabled                 *bool                               `json:"eksAddonEnabled,omitempty"`
	ManagedClusterConfig            *ManagedClusterConfig               `json:"managedClusterConfig,omitempty"`
	MaintenanceMode                 *bool                               `json:"maintenanceMode,omitempty"`
	MultiClusterK8SDashboardEnabled *bool                               `json:"multiClusterK8sDashboardEnabled,omitempty"`
	AutoscalerConfig                *AutoScalerConfig                   `json:"autoscalerConfig,omitempty"`
	Project                         string                              `json:"project,omitempty"`
	Compatibility                   *ClusterCompatibility               `json:"compatibility,omitempty"`
	ArgocdNotificationsSettings     *ClusterArgoCDNotificationsSettings `json:"argocdNotificationsSettings,omitempty"`
	ServerSideDiffEnabled           *bool                               `json:"serverSideDiffEnabled,omitempty"`
	MaintenanceModeExpiry           *metav1.Time                        `json:"maintenanceModeExpiry,omitempty"`
	PodInheritMetadata              *bool                               `json:"podInheritMetadata,omitempty"`
}

type KargoSpec struct {
	Description       string            `json:"description"`
	Version           string            `json:"version"`
	KargoInstanceSpec KargoInstanceSpec `json:"kargoInstanceSpec,omitempty"`
	Fqdn              string            `json:"fqdn,omitempty"`
	Subdomain         string            `json:"subdomain,omitempty"`
	OidcConfig        *KargoOidcConfig  `json:"oidcConfig,omitempty"`
}

type KargoPredefinedAccountClaimValue struct {
	Values []string `json:"values"`
}

type KargoPredefinedAccountData struct {
	Claims map[string]KargoPredefinedAccountClaimValue `json:"claims,omitempty"`
}

type KargoOidcConfig struct {
	// +optional
	Enabled *bool `json:"enabled"`
	// +optional
	DexEnabled *bool `json:"dexEnabled"`
	// +optional
	DexConfig string `json:"dexConfig"`
	// +optional
	DexConfigSecret map[string]Value `json:"dexConfigSecret"`
	// DexConfigSecretRef (MANUAL ADDITION — see banner at top of
	// file) references a Secret whose data is resolved at reconcile
	// time and forwarded to the Akuity gateway as the wire-shape
	// DexConfigSecret map. Mutually exclusive with the inline
	// DexConfigSecret above; CEL rule on KargoInstanceParameters
	// enforces it. Present here rather than on a hand-authored
	// shell so the user-facing YAML stays nested under
	// spec.oidcConfig alongside the other OIDC settings.
	// +optional
	DexConfigSecretRef *xpv1.LocalSecretReference `json:"dexConfigSecretRef,omitempty"`
	// +optional
	IssuerURL string `json:"issuerUrl"`
	// +optional
	ClientID string `json:"clientId"`
	// +optional
	CliClientID string `json:"cliClientId"`
	// +optional
	AdminAccount KargoPredefinedAccountData `json:"adminAccount"`
	// +optional
	ViewerAccount KargoPredefinedAccountData `json:"viewerAccount"`
	// +optional
	AdditionalScopes []string `json:"additionalScopes"`
	// +optional
	UserAccount KargoPredefinedAccountData `json:"userAccount"`
	// +optional
	ProjectCreatorAccount KargoPredefinedAccountData `json:"projectCreatorAccount"`
}

type Value struct {
	Value *string `json:"value,omitempty"`
}

type KargoIPAllowListEntry struct {
	Ip          string `json:"ip,omitempty"`
	Description string `json:"description,omitempty"`
}

type KargoAgentCustomization struct {
	AutoUpgradeDisabled *bool  `json:"autoUpgradeDisabled,omitempty"`
	Kustomization       string `json:"kustomization,omitempty"`
}

type KargoInstanceSpec struct {
	BackendIpAllowListEnabled  *bool                    `json:"backendIpAllowListEnabled,omitempty"`
	IpAllowList                []*KargoIPAllowListEntry `json:"ipAllowList,omitempty"`
	AgentCustomizationDefaults *KargoAgentCustomization `json:"agentCustomizationDefaults,omitempty"`
	DefaultShardAgent          string                   `json:"defaultShardAgent,omitempty"`
	GlobalCredentialsNs        []string                 `json:"globalCredentialsNs,omitempty"`
	GlobalServiceAccountNs     []string                 `json:"globalServiceAccountNs,omitempty"`
	AkuityIntelligence         *AkuityIntelligence      `json:"akuityIntelligence,omitempty"`
	GcConfig                   *GarbageCollectorConfig  `json:"gcConfig,omitempty"`
	PromoControllerEnabled     *bool                    `json:"promoControllerEnabled,omitempty"`
	Secrets                    SecretsManagementConfig  `json:"secrets,omitempty"`
	ArgocdUi                   *KargoArgoCDUIConfig     `json:"argocdUi,omitempty"`
}

type KargoArgoCDUIConfig struct {
	IdpGroupsMapping *bool `json:"idpGroupsMapping,omitempty"`
}

type AkuityIntelligence struct {
	AiSupportEngineerEnabled *bool    `json:"aiSupportEngineerEnabled,omitempty"`
	Enabled                  *bool    `json:"enabled,omitempty"`
	AllowedUsernames         []string `json:"allowedUsernames,omitempty"`
	AllowedGroups            []string `json:"allowedGroups,omitempty"`
	ModelVersion             string   `json:"modelVersion,omitempty"`
}

type GarbageCollectorConfig struct {
	MaxRetainedFreight      uint32 `json:"maxRetainedFreight,omitempty"`
	MaxRetainedPromotions   uint32 `json:"maxRetainedPromotions,omitempty"`
	MinFreightDeletionAge   uint32 `json:"minFreightDeletionAge,omitempty"`
	MinPromotionDeletionAge uint32 `json:"minPromotionDeletionAge,omitempty"`
}

type KargoAgentSize string

type KargoAgentSpec struct {
	Description string         `json:"description,omitempty"`
	Data        KargoAgentData `json:"data,omitempty"`
}

type KargoResources struct {
	Mem string `json:"mem,omitempty"`
	Cpu string `json:"cpu,omitempty"`
}

type KargoControllerAutoScalingConfig struct {
	ResourceMinimum *KargoResources `json:"resourceMinimum,omitempty"`
	ResourceMaximum *KargoResources `json:"resourceMaximum,omitempty"`
}

type KargoAutoscalerConfig struct {
	KargoController *KargoControllerAutoScalingConfig `json:"kargoController,omitempty"`
}

type KargoAgentData struct {
	Size                  KargoAgentSize         `json:"size,omitempty"`
	AutoUpgradeDisabled   *bool                  `json:"autoUpgradeDisabled,omitempty"`
	TargetVersion         string                 `json:"targetVersion,omitempty"`
	Kustomization         string                 `json:"kustomization,omitempty"`
	RemoteArgocd          string                 `json:"remoteArgocd,omitempty"`
	AkuityManaged         *bool                  `json:"akuityManaged,omitempty"`
	ArgocdNamespace       string                 `json:"argocdNamespace,omitempty"`
	SelfManagedArgocdUrl  string                 `json:"selfManagedArgocdUrl,omitempty"`
	AllowedJobSa          []string               `json:"allowedJobSa,omitempty"`
	MaintenanceMode       *bool                  `json:"maintenanceMode,omitempty"`
	MaintenanceModeExpiry *metav1.Time           `json:"maintenanceModeExpiry,omitempty"`
	PodInheritMetadata    *bool                  `json:"podInheritMetadata,omitempty"`
	AutoscalerConfig      *KargoAutoscalerConfig `json:"autoscalerConfig,omitempty"`
}

type PluginSpec struct {
	Version          string      `json:"version,omitempty"`
	Init             *Command    `json:"init,omitempty"`
	Generate         *Command    `json:"generate,omitempty"`
	Discover         *Discover   `json:"discover,omitempty"`
	Parameters       *Parameters `json:"parameters,omitempty"`
	PreserveFileMode *bool       `json:"preserveFileMode,omitempty"`
}

type Command struct {
	Command []string `json:"command,omitempty"`
	Args    []string `json:"args,omitempty"`
}

type Discover struct {
	Find     *Find  `json:"find,omitempty"`
	FileName string `json:"fileName,omitempty"`
}

type Find struct {
	Command []string `json:"command,omitempty"`
	Args    []string `json:"args,omitempty"`
	Glob    string   `json:"glob,omitempty"`
}

type Parameters struct {
	Static  []*ParameterAnnouncement `json:"static,omitempty"`
	Dynamic *Dynamic                 `json:"dynamic,omitempty"`
}

type Dynamic struct {
	Command []string `json:"command,omitempty"`
	Args    []string `json:"args,omitempty"`
}

type ParameterAnnouncement struct {
	Name           string            `json:"name,omitempty"`
	Title          string            `json:"title,omitempty"`
	Tooltip        string            `json:"tooltip,omitempty"`
	Required       *bool             `json:"required,omitempty"`
	ItemType       string            `json:"itemType,omitempty"`
	CollectionType string            `json:"collectionType,omitempty"`
	String         string            `json:"string,omitempty"`
	Array          []string          `json:"array,omitempty"`
	Map            map[string]string `json:"map,omitempty"`
}
