---
apiVersion: core.akuity.crossplane.io/v1alpha1
kind: KargoInstance
metadata:
  name: my-kargo
spec:
  forProvider:
    name: my-kargo
    kargo:
      description: "My Kargo instance."
      version: "v1.10.1-ak.0"
  providerConfigRef:
    name: akuity
