# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-kargo-dex
#   namespace: crossplane-system
# type: Opaque
# stringData:
#   clientSecret: REPLACE_ME
---
apiVersion: core.akuity.crossplane.io/v1alpha1
kind: KargoInstance
metadata:
  name: my-kargo-oidc
spec:
  forProvider:
    name: my-kargo-oidc
    kargo:
      description: "My Kargo instance with OIDC."
      version: "v1.8.1"
      oidcConfig:
        enabled: true
        dexEnabled: false
        issuerUrl: "https://id.example.com"
        clientId: "my-kargo"
        cliClientId: "my-kargo-cli"
        dexConfigSecretRef:
          namespace: crossplane-system
          name: my-kargo-dex
        additionalScopes:
          - groups
        adminAccount:
          claims:
            groups:
              values:
                - platform-admins
        viewerAccount:
          claims:
            groups:
              values:
                - platform-viewers
  providerConfigRef:
    name: akuity
