apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: provider-crossplane-akuity-v1alpha2
  labels:
    provider: provider-crossplane-akuity
    apiGroup: core.m.akuity.crossplane.io
spec:
  activate:
    - clusters.core.m.akuity.crossplane.io
    - instances.core.m.akuity.crossplane.io
    - instanceipallowlists.core.m.akuity.crossplane.io
    - kargoinstances.core.m.akuity.crossplane.io
    - kargoagents.core.m.akuity.crossplane.io
    - kargodefaultshardagents.core.m.akuity.crossplane.io
