//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	crossplanev1alpha1 "github.com/akuityio/provider-crossplane-akuity/internal/types/generated/crossplane/v1alpha1"
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationsHealth) DeepCopyInto(out *ApplicationsHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationsHealth.
func (in *ApplicationsHealth) DeepCopy() *ApplicationsHealth {
	if in == nil {
		return nil
	}
	out := new(ApplicationsHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationsStatus) DeepCopyInto(out *ApplicationsStatus) {
	*out = *in
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(ApplicationsHealth)
		**out = **in
	}
	if in.SyncStatus != nil {
		in, out := &in.SyncStatus, &out.SyncStatus
		*out = new(ApplicationsSyncStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationsStatus.
func (in *ApplicationsStatus) DeepCopy() *ApplicationsStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationsSyncStatus) DeepCopyInto(out *ApplicationsSyncStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationsSyncStatus.
func (in *ApplicationsSyncStatus) DeepCopy() *ApplicationsSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationsSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObservation) DeepCopyInto(out *ClusterObservation) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.AgentState.DeepCopyInto(&out.AgentState)
	out.HealthStatus = in.HealthStatus
	out.ReconciliationStatus = in.ReconciliationStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObservation.
func (in *ClusterObservation) DeepCopy() *ClusterObservation {
	if in == nil {
		return nil
	}
	out := new(ClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObservationAgentHealthStatus) DeepCopyInto(out *ClusterObservationAgentHealthStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObservationAgentHealthStatus.
func (in *ClusterObservationAgentHealthStatus) DeepCopy() *ClusterObservationAgentHealthStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterObservationAgentHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObservationAgentState) DeepCopyInto(out *ClusterObservationAgentState) {
	*out = *in
	if in.Statuses != nil {
		in, out := &in.Statuses, &out.Statuses
		*out = make(map[string]ClusterObservationAgentHealthStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObservationAgentState.
func (in *ClusterObservationAgentState) DeepCopy() *ClusterObservationAgentState {
	if in == nil {
		return nil
	}
	out := new(ClusterObservationAgentState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObservationStatus) DeepCopyInto(out *ClusterObservationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObservationStatus.
func (in *ClusterObservationStatus) DeepCopy() *ClusterObservationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParameters) DeepCopyInto(out *ClusterParameters) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	in.ClusterSpec.DeepCopyInto(&out.ClusterSpec)
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.KubeConfigSecretRef = in.KubeConfigSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParameters.
func (in *ClusterParameters) DeepCopy() *ClusterParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIpAllowList) DeepCopyInto(out *InstanceIpAllowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIpAllowList.
func (in *InstanceIpAllowList) DeepCopy() *InstanceIpAllowList {
	if in == nil {
		return nil
	}
	out := new(InstanceIpAllowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceIpAllowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIpAllowListList) DeepCopyInto(out *InstanceIpAllowListList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceIpAllowList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIpAllowListList.
func (in *InstanceIpAllowListList) DeepCopy() *InstanceIpAllowListList {
	if in == nil {
		return nil
	}
	out := new(InstanceIpAllowListList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceIpAllowListList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIpAllowListObservation) DeepCopyInto(out *InstanceIpAllowListObservation) {
	*out = *in
	if in.AllowList != nil {
		in, out := &in.AllowList, &out.AllowList
		*out = make([]*crossplanev1alpha1.IPAllowListEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(crossplanev1alpha1.IPAllowListEntry)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIpAllowListObservation.
func (in *InstanceIpAllowListObservation) DeepCopy() *InstanceIpAllowListObservation {
	if in == nil {
		return nil
	}
	out := new(InstanceIpAllowListObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIpAllowListParameters) DeepCopyInto(out *InstanceIpAllowListParameters) {
	*out = *in
	if in.InstanceRef != nil {
		in, out := &in.InstanceRef, &out.InstanceRef
		*out = new(LocalReference)
		**out = **in
	}
	if in.AllowList != nil {
		in, out := &in.AllowList, &out.AllowList
		*out = make([]*crossplanev1alpha1.IPAllowListEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(crossplanev1alpha1.IPAllowListEntry)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIpAllowListParameters.
func (in *InstanceIpAllowListParameters) DeepCopy() *InstanceIpAllowListParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceIpAllowListParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIpAllowListSpec) DeepCopyInto(out *InstanceIpAllowListSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIpAllowListSpec.
func (in *InstanceIpAllowListSpec) DeepCopy() *InstanceIpAllowListSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceIpAllowListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIpAllowListStatus) DeepCopyInto(out *InstanceIpAllowListStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIpAllowListStatus.
func (in *InstanceIpAllowListStatus) DeepCopy() *InstanceIpAllowListStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceIpAllowListStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceList) DeepCopyInto(out *InstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceList.
func (in *InstanceList) DeepCopy() *InstanceList {
	if in == nil {
		return nil
	}
	out := new(InstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceObservation) DeepCopyInto(out *InstanceObservation) {
	*out = *in
	out.HealthStatus = in.HealthStatus
	out.ReconciliationStatus = in.ReconciliationStatus
	in.ArgoCD.DeepCopyInto(&out.ArgoCD)
	if in.ArgoCDConfigMap != nil {
		in, out := &in.ArgoCDConfigMap, &out.ArgoCDConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDImageUpdaterConfigMap != nil {
		in, out := &in.ArgoCDImageUpdaterConfigMap, &out.ArgoCDImageUpdaterConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDImageUpdaterSSHConfigMap != nil {
		in, out := &in.ArgoCDImageUpdaterSSHConfigMap, &out.ArgoCDImageUpdaterSSHConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDNotificationsConfigMap != nil {
		in, out := &in.ArgoCDNotificationsConfigMap, &out.ArgoCDNotificationsConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDRBACConfigMap != nil {
		in, out := &in.ArgoCDRBACConfigMap, &out.ArgoCDRBACConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDSSHKnownHostsConfigMap != nil {
		in, out := &in.ArgoCDSSHKnownHostsConfigMap, &out.ArgoCDSSHKnownHostsConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDTLSCertsConfigMap != nil {
		in, out := &in.ArgoCDTLSCertsConfigMap, &out.ArgoCDTLSCertsConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigManagementPlugins != nil {
		in, out := &in.ConfigManagementPlugins, &out.ConfigManagementPlugins
		*out = make(map[string]crossplanev1alpha1.ConfigManagementPlugin, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ApplicationsStatus != nil {
		in, out := &in.ApplicationsStatus, &out.ApplicationsStatus
		*out = new(ApplicationsStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceObservation.
func (in *InstanceObservation) DeepCopy() *InstanceObservation {
	if in == nil {
		return nil
	}
	out := new(InstanceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceObservationStatus) DeepCopyInto(out *InstanceObservationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceObservationStatus.
func (in *InstanceObservationStatus) DeepCopy() *InstanceObservationStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceParameters) DeepCopyInto(out *InstanceParameters) {
	*out = *in
	if in.ArgoCD != nil {
		in, out := &in.ArgoCD, &out.ArgoCD
		*out = new(crossplanev1alpha1.ArgoCD)
		(*in).DeepCopyInto(*out)
	}
	if in.ArgoCDConfigMap != nil {
		in, out := &in.ArgoCDConfigMap, &out.ArgoCDConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDImageUpdaterConfigMap != nil {
		in, out := &in.ArgoCDImageUpdaterConfigMap, &out.ArgoCDImageUpdaterConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDImageUpdaterSSHConfigMap != nil {
		in, out := &in.ArgoCDImageUpdaterSSHConfigMap, &out.ArgoCDImageUpdaterSSHConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDNotificationsConfigMap != nil {
		in, out := &in.ArgoCDNotificationsConfigMap, &out.ArgoCDNotificationsConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDRBACConfigMap != nil {
		in, out := &in.ArgoCDRBACConfigMap, &out.ArgoCDRBACConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDSSHKnownHostsConfigMap != nil {
		in, out := &in.ArgoCDSSHKnownHostsConfigMap, &out.ArgoCDSSHKnownHostsConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArgoCDTLSCertsConfigMap != nil {
		in, out := &in.ArgoCDTLSCertsConfigMap, &out.ArgoCDTLSCertsConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigManagementPlugins != nil {
		in, out := &in.ConfigManagementPlugins, &out.ConfigManagementPlugins
		*out = make(map[string]crossplanev1alpha1.ConfigManagementPlugin, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ArgoCDSecretRef != nil {
		in, out := &in.ArgoCDSecretRef, &out.ArgoCDSecretRef
		*out = new(v1.LocalSecretReference)
		**out = **in
	}
	if in.ArgoCDNotificationsSecretRef != nil {
		in, out := &in.ArgoCDNotificationsSecretRef, &out.ArgoCDNotificationsSecretRef
		*out = new(v1.LocalSecretReference)
		**out = **in
	}
	if in.ArgoCDImageUpdaterSecretRef != nil {
		in, out := &in.ArgoCDImageUpdaterSecretRef, &out.ArgoCDImageUpdaterSecretRef
		*out = new(v1.LocalSecretReference)
		**out = **in
	}
	if in.ApplicationSetSecretRef != nil {
		in, out := &in.ApplicationSetSecretRef, &out.ApplicationSetSecretRef
		*out = new(v1.LocalSecretReference)
		**out = **in
	}
	if in.RepoCredentialSecretRefs != nil {
		in, out := &in.RepoCredentialSecretRefs, &out.RepoCredentialSecretRefs
		*out = make([]NamedLocalSecretReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RepoTemplateCredentialSecretRefs != nil {
		in, out := &in.RepoTemplateCredentialSecretRefs, &out.RepoTemplateCredentialSecretRefs
		*out = make([]NamedLocalSecretReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceParameters.
func (in *InstanceParameters) DeepCopy() *InstanceParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoAgent) DeepCopyInto(out *KargoAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoAgent.
func (in *KargoAgent) DeepCopy() *KargoAgent {
	if in == nil {
		return nil
	}
	out := new(KargoAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KargoAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoAgentList) DeepCopyInto(out *KargoAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KargoAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoAgentList.
func (in *KargoAgentList) DeepCopy() *KargoAgentList {
	if in == nil {
		return nil
	}
	out := new(KargoAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KargoAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoAgentObservation) DeepCopyInto(out *KargoAgentObservation) {
	*out = *in
	out.HealthStatus = in.HealthStatus
	out.ReconciliationStatus = in.ReconciliationStatus
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoAgentObservation.
func (in *KargoAgentObservation) DeepCopy() *KargoAgentObservation {
	if in == nil {
		return nil
	}
	out := new(KargoAgentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoAgentParameters) DeepCopyInto(out *KargoAgentParameters) {
	*out = *in
	if in.KargoInstanceRef != nil {
		in, out := &in.KargoInstanceRef, &out.KargoInstanceRef
		*out = new(LocalReference)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoAgentParameters.
func (in *KargoAgentParameters) DeepCopy() *KargoAgentParameters {
	if in == nil {
		return nil
	}
	out := new(KargoAgentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoAgentResourceSpec) DeepCopyInto(out *KargoAgentResourceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoAgentResourceSpec.
func (in *KargoAgentResourceSpec) DeepCopy() *KargoAgentResourceSpec {
	if in == nil {
		return nil
	}
	out := new(KargoAgentResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoAgentStatus) DeepCopyInto(out *KargoAgentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoAgentStatus.
func (in *KargoAgentStatus) DeepCopy() *KargoAgentStatus {
	if in == nil {
		return nil
	}
	out := new(KargoAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoDefaultShardAgent) DeepCopyInto(out *KargoDefaultShardAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoDefaultShardAgent.
func (in *KargoDefaultShardAgent) DeepCopy() *KargoDefaultShardAgent {
	if in == nil {
		return nil
	}
	out := new(KargoDefaultShardAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KargoDefaultShardAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoDefaultShardAgentList) DeepCopyInto(out *KargoDefaultShardAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KargoDefaultShardAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoDefaultShardAgentList.
func (in *KargoDefaultShardAgentList) DeepCopy() *KargoDefaultShardAgentList {
	if in == nil {
		return nil
	}
	out := new(KargoDefaultShardAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KargoDefaultShardAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoDefaultShardAgentObservation) DeepCopyInto(out *KargoDefaultShardAgentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoDefaultShardAgentObservation.
func (in *KargoDefaultShardAgentObservation) DeepCopy() *KargoDefaultShardAgentObservation {
	if in == nil {
		return nil
	}
	out := new(KargoDefaultShardAgentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoDefaultShardAgentParameters) DeepCopyInto(out *KargoDefaultShardAgentParameters) {
	*out = *in
	if in.KargoInstanceRef != nil {
		in, out := &in.KargoInstanceRef, &out.KargoInstanceRef
		*out = new(LocalReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoDefaultShardAgentParameters.
func (in *KargoDefaultShardAgentParameters) DeepCopy() *KargoDefaultShardAgentParameters {
	if in == nil {
		return nil
	}
	out := new(KargoDefaultShardAgentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoDefaultShardAgentSpec) DeepCopyInto(out *KargoDefaultShardAgentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoDefaultShardAgentSpec.
func (in *KargoDefaultShardAgentSpec) DeepCopy() *KargoDefaultShardAgentSpec {
	if in == nil {
		return nil
	}
	out := new(KargoDefaultShardAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoDefaultShardAgentStatus) DeepCopyInto(out *KargoDefaultShardAgentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoDefaultShardAgentStatus.
func (in *KargoDefaultShardAgentStatus) DeepCopy() *KargoDefaultShardAgentStatus {
	if in == nil {
		return nil
	}
	out := new(KargoDefaultShardAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoInstance) DeepCopyInto(out *KargoInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoInstance.
func (in *KargoInstance) DeepCopy() *KargoInstance {
	if in == nil {
		return nil
	}
	out := new(KargoInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KargoInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoInstanceList) DeepCopyInto(out *KargoInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KargoInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoInstanceList.
func (in *KargoInstanceList) DeepCopy() *KargoInstanceList {
	if in == nil {
		return nil
	}
	out := new(KargoInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KargoInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoInstanceObservation) DeepCopyInto(out *KargoInstanceObservation) {
	*out = *in
	out.HealthStatus = in.HealthStatus
	out.ReconciliationStatus = in.ReconciliationStatus
	in.Kargo.DeepCopyInto(&out.Kargo)
	if in.RepoCredsAppliedAt != nil {
		in, out := &in.RepoCredsAppliedAt, &out.RepoCredsAppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoInstanceObservation.
func (in *KargoInstanceObservation) DeepCopy() *KargoInstanceObservation {
	if in == nil {
		return nil
	}
	out := new(KargoInstanceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoInstanceParameters) DeepCopyInto(out *KargoInstanceParameters) {
	*out = *in
	in.Kargo.DeepCopyInto(&out.Kargo)
	if in.KargoConfigMap != nil {
		in, out := &in.KargoConfigMap, &out.KargoConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.KargoSecretRef != nil {
		in, out := &in.KargoSecretRef, &out.KargoSecretRef
		*out = new(v1.LocalSecretReference)
		**out = **in
	}
	if in.KargoRepoCredentialSecretRefs != nil {
		in, out := &in.KargoRepoCredentialSecretRefs, &out.KargoRepoCredentialSecretRefs
		*out = make([]KargoRepoCredentialSecretRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoInstanceParameters.
func (in *KargoInstanceParameters) DeepCopy() *KargoInstanceParameters {
	if in == nil {
		return nil
	}
	out := new(KargoInstanceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoInstanceResourceSpec) DeepCopyInto(out *KargoInstanceResourceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoInstanceResourceSpec.
func (in *KargoInstanceResourceSpec) DeepCopy() *KargoInstanceResourceSpec {
	if in == nil {
		return nil
	}
	out := new(KargoInstanceResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoInstanceStatus) DeepCopyInto(out *KargoInstanceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoInstanceStatus.
func (in *KargoInstanceStatus) DeepCopy() *KargoInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(KargoInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KargoRepoCredentialSecretRef) DeepCopyInto(out *KargoRepoCredentialSecretRef) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KargoRepoCredentialSecretRef.
func (in *KargoRepoCredentialSecretRef) DeepCopy() *KargoRepoCredentialSecretRef {
	if in == nil {
		return nil
	}
	out := new(KargoRepoCredentialSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalReference) DeepCopyInto(out *LocalReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalReference.
func (in *LocalReference) DeepCopy() *LocalReference {
	if in == nil {
		return nil
	}
	out := new(LocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameRef) DeepCopyInto(out *NameRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameRef.
func (in *NameRef) DeepCopy() *NameRef {
	if in == nil {
		return nil
	}
	out := new(NameRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedLocalSecretReference) DeepCopyInto(out *NamedLocalSecretReference) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedLocalSecretReference.
func (in *NamedLocalSecretReference) DeepCopy() *NamedLocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(NamedLocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatusCode) DeepCopyInto(out *ResourceStatusCode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatusCode.
func (in *ResourceStatusCode) DeepCopy() *ResourceStatusCode {
	if in == nil {
		return nil
	}
	out := new(ResourceStatusCode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}
