---
apiVersion: core.akuity.crossplane.io/v1alpha1
kind: KargoDefaultShardAgent
metadata:
  name: my-kargo-default-shard
spec:
  forProvider:
    # The Kargo instance ID can be hardcoded or resolved via a
    # KargoInstance MR in the same Crossplane cluster.
    # kargoInstanceId: "my-kargo-instance-id"
    kargoInstanceRef:
      name: "my-kargo"
    agentName: "shard-a"
  providerConfigRef:
    name: akuity
