---
apiVersion: akuity.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: akuity
spec:
  organizationId: REPLACE_ME
  credentialsSecretRef:
    namespace: crossplane-system
    name: akuity-provider-secret
    key: credentials
