---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: akuity-provider-secret
type: Opaque
stringData:
  credentials: |
    {"apiKeyId":"REPLACE_ME","apiKeySecret":"REPLACE_ME"}
