---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: akuity
spec:
  package: us-docker.pkg.dev/akuity/crossplane/provider:REPLACE_WITH_VERSION
  runtimeConfigRef:
    name: akuity
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: akuity
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          securityContext:
            fsGroup: 2000
          containers:
            - name: package-runtime
              args:
                - --debug
