---
apiVersion: core.akuity.crossplane.io/v1alpha1
kind: KargoAgent
metadata:
  name: my-kargo-agent-auto
spec:
  forProvider:
    kargoInstanceRef:
      name: "my-kargo"
    name: "my-kargo-agent-auto"
    namespace: "kargo"
    kargoAgentSpec:
      description: "Kargo agent with controller autoscaling bounds."
      data:
        size: "auto"
        autoUpgradeDisabled: false
        autoscalerConfig:
          kargoController:
            resourceMinimum:
              cpu: "500m"
              mem: "1Gi"
            resourceMaximum:
              cpu: "2000m"
              mem: "4Gi"
  providerConfigRef:
    name: akuity
